### ISSUE TITLE
If oneway, cyclist could dismount and go on foot

### ISSUE THREAD

**Issue by tiagofassoni** [graphhopper/graphhopper#409] opened 2015-05-12 00:50 UTC
I'm making a routing app for São Paulo and we have several cases where the most useful way would be for the cyclist to dismount and go through the sidewalk.

As far as I've been able to understand, if it's a highway=pedestrian, the bike encoder understands the cyclist should go dismounted.

But if it's a oneway street, the encoder tells me to go around it. 

I want to create a encoder that addresses this, but I need help.

To make the cyclist go through the sidewalk when it's a oneway street, I could remove the oneway restriction and instead change it's speed to walking speed. But I think I'd lose the nice notification of "dismount". Any sugestions?

**Comment by zhiqiangZHAO** [comment] 2015-05-12 01:00
Sounds this is a new kind of guidance. "dismount from bike and walk". You can just encode this in WayType. Look at BikeCommonFlagEncoder, there is already a PUSHING_SECTION, which I think it's the same thing.

private enum WayType
    {
        ROAD(0),
        PUSHING_SECTION(1),
        CYCLEWAY(2),
        OTHER_SMALL_WAY(3);

**Comment by tiagofassoni** [comment] 2015-05-12 01:30
But there is one issue there: the way only has guidance "dismount from bike and walk" if the cyclist is going on the contraflow.

**Comment by tiagofassoni** [comment] 2015-05-12 01:30
So I don't think it should be a new type of way.

**Comment by zhiqiangZHAO** [comment] 2015-05-12 01:52
I see. Then just use bitMasks from abstractFlagEncoder:
    protected long forwardBit;
    protected long backwardBit;
    protected long directionBitMask;

I remember in Bike2WeightFlagEncoder, there are two speed values into an edge to support avoiding too much incline. Similar to your requirement.

Just implement your own flagEncoder. add a bitFlag to show whether need dismount in this direction.

**Comment by karussell** [comment] 2015-05-12 06:29
You could preprocess the graph, allow both directions and mark them as pushing section and it will contain such notation.

Note, this is a duplicate of #196

**Closed by karussell** 2015-05-12 06:29 UTC
