### ISSUE TITLE
Reduce/Increase Continue Turn Instructions

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper#895] opened 2016-12-05 07:09 UTC
Currently, the turn instruction generation is not perfect. The most prominent issue IMHO are too many continue instructions. However, this opinion seems to be a bit controversial, according to #94 and #790 .

Personally, I could live without continue instructions, at all (there might be exceptions were this behavior leads to issues - I think it should work in most cases). So basically the question is how should we proceed with this issue?

I would also be fine with making this configurable, either per Profile/Encoder or with a simple config line like:
`number_of_instructions=none|medium (current algorithm)|frequent (see #790)`

**Comment by karussell** [comment] 2016-12-05 10:12
Isn't this a duplicate of #94?

> I would also be fine with making this configurable

Making things here configurable is overkill. Every weighting should be able to control somehow the creation of turn instructions.

**Comment by boldtrn** [comment] 2016-12-05 10:19
> Isn't this a duplicate of #94? Or why is a new issue about turn instructions necessary?

I had the same thought. But #94 is mostly about adding instructions that are missing, this issue is more about removing unnecessary instructions, but we can close this and discuss in #94 if you want? I just didn't want to make the other issue too complex.

>  Every weighting should be able to control somehow the creation of turn instructions.

Interesting approach. Why would you put that in the weighting? Fastest for a car, might want to produce different instructions than fastest for pedestrians or as in @don-philipe's example fastest for visually impaired.

**Comment by karussell** [comment] 2016-12-05 10:24
> I just didn't want to make the other issue too complex.

I think, both issues can be improved at the same time when improving turn instruction handling.

> Why would you put that in the weighting?

Because at some point we have only one (data)encoder used from multiple `Weighting`s. And as a `Weighting` can also block roads via infinity, or being used for car or foot we need this difference there or in a new InstructionCreator or renaming Weighting etc

**Closed** 2016-12-05 10:26 UTC
