### ISSUE TITLE
avoid map zoom out every time a new point is added

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#775] opened 2016-08-23 07:43 UTC
It would also be nice if the map did not zoom out every time a new point is added.

**Comment by fbonzon** [comment] 2016-08-23 20:31
> It would also be nice if the map did not zoom out every time a new point is added.

This feature, I have actually recently implemented on my GraphHopper fork. I will isolate needed changes and send a PR !

I did it with an additional `allow_zoom_out` parameter in GHRequest, initially `true`, then set to `false` if the request is triggered with a right-click on the map.

**Comment by devemux86** [comment] 2016-08-24 06:05
>It would also be nice if the map did not zoom out every time a new point is added.

Doesn't the zoom adjustment happens after each route geometry calculation?

**Comment by fbonzon** [comment] 2016-08-24 06:17
Yes. Currently, zoom adjustment happens after every route calculation, so that the entire route fits the map. When you were zoomed in even closer before the route calculation, staying at that zoom level is often desirable, instead of being zoomed out to see the entire route.

**Comment by devemux86** [comment] 2016-08-24 06:23
Then an external setting wouldn't be more appropriate, as the auto-zoom is app's responsibility getting the result, instead of passing options to GH core?

**Comment by fbonzon** [comment] 2016-08-24 06:41
Correct. That's the idea. Only the webapp would be changed. There is already a `do_zoom` parameter actually in the JavaScript code, for doing any zoom (in or out): https://github.com/graphhopper/graphhopper/blob/1e30238e76bacbe506593c6277e768d8f810547a/web/src/main/webapp/js/graphhopper/GHRequest.js#L40
I'm adding a new similar parameter for zoom out only.

**Comment by karussell** [comment] 2016-08-24 12:28
> Yes. Currently, zoom adjustment happens after every route calculation

It does not happen if you just drag the markers. Couldn't we use the same mechanism when adding new points? I think I introduced the zoom parameter for this pupose

**Comment by fbonzon** [comment] 2016-08-24 16:02
Correct, we could do the same. Is actually what I did, but I added a new parameter specific for zoom out. do_zoom forbids zooms in both directions.

In case adding new points through mouse click would result in a zoom in, I still allow the zoom in in my implementation, because it is not harmful. Thus is a different parameter, to disallow an automatic zoom out only. Do you agree?

**Comment by ammagamma** [comment] 2016-08-25 15:46
> intermediate points should be added just between the two closest points to the newly-added one

By 'two closest points' do you mean the two closest points in terms of a linear connection or the two points that are connected by the two shortest possible paths ? The first version would of course be easier to realize and would probably be sufficient if the user knows in which order he wants to travel the different destinations. If the order is not as he intended he can easily change the order especially if the intermediate points get numbered in the side bar (as you suggest). The second version would be interesting in case the user adds a destination and wants the shortest connection regardless of the final order of the different points. I n my opinion it would be best to start with the first version and make it the default.

**Comment by karussell** [comment] 2016-08-25 18:21
> By 'two closest points' do you mean the two closest points in terms of a linear connection or the two points that are connected by the two shortest possible paths 

I think it should work like: user clicks&drags then determine location and do "snap to a coordinate of the route", now insert a new via point at the correct position between potential other via points. See the prototype mentioned in my initial comment or a version without the dragging feature at kurviger.de

> The second version would be interesting in case the user adds a destination and wants the shortest connection regardless of the final order of the different points.

Do you mean sorting the locations via TSP? This should not be our aim :)

**Comment by ammagamma** [comment] 2016-08-25 20:12
I was just wondering if we should use the beeline (Luftlinie) or the actual length of the shortest drivable route as distance metric to decide which are the 'two closest points'. Consider [route1](https://kurviger.de/?point=52.087629%2C11.808929&point=52.027782%2C11.743355&point=52.008661%2C11.849699&point=52.009929%2C11.852789&point=51.977743%2C11.873217&locale=de&vehicle=motorcycle&weighting=curvature&additional_weighting=&elevation=true&layer=Omniscale) on kurviger.de. Adding another intemediate point in "Ranies" (just west from points 2&3) results in [route2](https://kurviger.de/?point=52.087629%2C11.808929&point=52.027782%2C11.743355&point=52.016796%2C11.827984&point=52.008661%2C11.849699&point=52.009929%2C11.852789&point=51.977743%2C11.873217&locale=de&vehicle=motorcycle&weighting=curvature&additional_weighting=&elevation=true&layer=Omniscale) which uses "Ranies" as first intermediate point. However, if the intermediate point would be simply added as a stopover between the two closest (by means of the beeline) points (points 3&4 in route2) we would get [route3](https://kurviger.de/?point=52.087629%2C11.808929&point=52.027782%2C11.743355&point=52.008661%2C11.849699&point=52.016796%2C11.827984&point=52.009929%2C11.852789&point=51.977743%2C11.873217&locale=de&vehicle=motorcycle&weighting=curvature&additional_weighting=&elevation=true&layer=Omniscale), which is much longer and only makes sense if this specific order of the intermediate points is really wanted. I thought it would be sufficient to simply use the beeline to find the two 'closest' points nonetheless as it is easy to manually reorder the intermediate points in the few cases the results are not as desired. It saves the effort of calculating the routes from the point that is about to be added to all the others. 

> Do you mean sorting the locations via TSP?

I did not mean TSP for all locations, but rather meant what kurviger.de apparently does: When a new point is chosen as intermediate it chooses its position such that the length of the total route is minimized (route2 instead of route3 in the above example). This I guess is done by finding the two existing points that are closest by means of the length of the route to get there (and not the beeline) (?).

**Comment by ammagamma** [comment] 2016-08-25 20:15
> I think it should work like: user clicks&drags then determine location and do "snap to a coordinate of the route", now insert a new via point at the correct position between potential other via points

If we want to be able to drag the route, we first have to figure out which points the dragged route segment connects. I have not looked into this and I am not sure if this information is already available for all the route segments  after the first routing request. If we only know the intermediate points (and not the relation between the segments and the points) we could do the following:
- mousedown/begin of drag: use this coordinate to find the two closest points A and B (by means of real routes). This asserts we are modifying the correct segment.
- mouseup/end of drag: use this coordinate for the new intermediate point that is inserted between the two points A and B

**Comment by ammagamma** [comment] 2016-08-25 20:20
I would prefer the clicking method using the beeline distance to find the two closest points. It is the most simple solution and works in almost every case. The dragging on kasheftin is not very fun to use in my opinion (probably even more so on a phone).

**Comment by karussell** [comment] 2016-08-25 21:36
With "beeline" you mean finding out the closest point on the route or finding the closest via-point? I guess the first option and then yes, this is what I also think is the simplest solution for now.

BTW: the [TSP version](https://www.youtube.com/watch?v=ODZ6Sy66GMQ) has a really nice effect :)

**Comment by ammagamma** [comment] 2016-08-26 07:45
In this commit edf95560f9a44fd2e9b581bae4bed8068f5713da new intermediate points are added by clicking the map (as it used to be so far). However, each new intermediate point is now inserted between the two closest of the start/end/via-points that exist before the new point is added. 'Closest' is defined in terms of the beeline distance. By beeline distance I mean the distance between two points as it is calculated by the [Haversine formula](https://en.wikipedia.org/wiki/Haversine_formula), which for short distances corresponds to the distance you get if  you draw a straight line between two points on the map. Maybe you can just try it out and tell me if this is what you had imagined ;)

**Comment by karussell** [comment] 2016-08-26 11:13
This is a beautiful short snippet :) :+1: !

Some minor problem I stumbled over (inserted as "1" where it should be "2") which I currently debug. E.g. use [this route](http://localhost:8989/?point=49.453843%2C10.640259&point=49.386843%2C11.46286&point=48.777913%2C12.332153&point=48.777913%2C12.332153&point=48.777913%2C12.332153&point=48.777913%2C12.332153) in Bavaria and put a new intermediate point at "Neuenmark in der Oberpfalz". 

And the input fields on the right do not seem to change.

**Comment by karussell** [comment] 2016-08-26 12:24
Also do you think it is too slow to iterate over all points of the geometry (response) instead of the via-points from the request? Hmmh, ok, this gets even harder for alternative routes...

**Comment by ammagamma** [comment] 2016-08-26 18:39
> This is a beautiful short snippet :) :+1: !

Thanks!

> Some minor problem I stumbled over (inserted as "1" where it should be "2") which I currently debug. E.g. use this route in Bavaria and put a new intermediate point at "Neuenmark in der Oberpfalz".

I might be able to look further into this next week, but feel free to continue working on this if you want!

> And the input fields on the right do not seem to change.

Ok, yes I simply added the snippet so we can agree on how adding intermediate points should roughly work and I did not pay attention to the sidebar yet.

> Also do you think it is too slow to iterate over all points of the geometry (response) instead of the via-points from the request? Hmmh, ok, this gets even harder for alternative routes...

I probably would not so much be concerned about that it is too slow to iterate over all points (they are stored in the map layer I think), but once the closest point of the geometry is found you have to relate it somehow to the via-points (find out which via points are connected by the route segment you found to be the closest to the new points). I have not looked into this yet.

**Comment by karussell** [comment] 2016-08-30 13:53
Ups, forgot to reply @fbonzon 

> In case adding new points through mouse click would result in a zoom in

When would this be the case?

**Comment by fbonzon** [comment] 2016-08-30 14:55
@karussell Consider these 2 cases. Do you agree with the "Expected" sections? I will send PR to change behavior in case 1) if you agree.

### 1) Adding a point results in zoom out

#### Steps to reproduce

- Go [here](https://graphhopper.com/maps/?point=Berlin%2C%20Germany&point=52.511415%2C13.295174&locale=en-US&vehicle=bike&weighting=fastest&elevation=true&use_miles=false&layer=Omniscale)
- **Click twice on the [+] icon** to zoom in 2 levels. The static link URLs in GraphHopper Maps do not save the zoom levels, thus this step is required to reproduce the zoom out behaviour.
- Right click somewhere in the middle of the screen, and select "Set intermediate"

#### Actual

Zoom out occurs

#### Expected

No zoom out occurs. Zoom level stays the same.


### 2) Adding a point results in zoom in

#### Steps to reproduce

- Go [here](https://graphhopper.com/maps/?point=Berlin%2C%20Germany&point=52.511415%2C13.295174&locale=en-US&vehicle=bike&weighting=fastest&elevation=true&use_miles=false&layer=Omniscale)
- **Click twice on the [-] icon** to zoom out 2 levels. The static link URLs in GraphHopper Maps do not save the zoom levels, thus this step is required to reproduce the zoom in behaviour.
- Right click somewhere in the middle of the screen, between the existing start and end points, and select "Set intermediate"

#### Actual

Zoom in occurs

#### Expected

Actual is fine, same.

**Comment by karussell** [comment] 2016-08-30 15:27
Don't you think this makes it too complex? I would be fine if it does not zoom in both cases. Maybe we add a button that "zooms to fit the whole route" instead?

**Comment by fbonzon** [comment] 2016-08-30 15:37
Both implementations make sense (no zoom either direction, or zoom in only), or also add a button to manually fit the route to the viewport. That's your decision in the end, I will not argue.

I was personally annoyed by the zoom out behavior when using GraphHopper, so I added code to disable that. When I'm zoomed in deeply to precisely add intermediate points, this zoom out is clearly not wanted. I think we agree here. Your first post in this thread ("It would also be nice if the map did not zoom out every time a new point is added.") mentions this case only.

When adding a new point results in zoom in, I am not annoyed. I think it's even better. I still see as much of the route as I was seeing before, and I don't work less precisely as before (even the contrary, since I was zoomed in).

**Comment by karussell** [comment] 2016-08-30 15:55
Ok. As you are good with both options :) I would slightly prefer to have just one parameter (`do_zoom`) and disable zooming it in both cases. Plus provide a "fit to route" button (e.g. below zoom buttons?), which should be very simple via:
```js
map.fitBounds(polyline.getBounds());
```

**Comment by ammagamma** [comment] 2016-09-10 10:21
> Some minor problem I stumbled over (inserted as "1" where it should be "2") which I currently debug. E.g. use this route in Bavaria and put a new intermediate point at "Neuenmark in der Oberpfalz".

I fixed this here: https://github.com/graphhopper/graphhopper/pull/791

**Comment by jeffrey-friedl** [comment] 2017-04-19 11:45
Hi. Did "do_zoom" or the like ever make it public? I'd love to be able to disable auto-zoom when working with the map.   Also, is there any chance that the markers along the side can be numbered like they are on the map? These two changes would make things perfect..... 

Thanks so much,
Jeffrey

**Comment by boldtrn** [comment] 2017-04-19 23:54
> Did "do_zoom" or the like ever make it public?

Not to my knowledge, but you are more than welcome to create a PR :).

**Comment by fbonzon** [comment] 2018-05-05 16:06
@karussell Can we have separate issue for each improvement suggested here ? Will be easier to discuss and follow status.

I suggest we keep this one for the zoom problem, since we discuss it above. I'll address it, you can assign to me. Please modify this issue title, and edit first message in this issue to keep only the sentence about zoom.

For the 3 remaining:
- "intermediate points should be added just between the two closest points ". This was fixed.
- "It would be nice if the list of points along the left were numbered, just as the points are on the actual map" → Create new issue
- "in addition to "Set as End", an option to "Extend route To" would be very useful. This would turn the current end point into an intermediate point, then set the selected location as the end point." → Create new issue

**Comment by easbar** [comment] 2020-01-28 12:10
After opening the separate issues #1359 and #1360 this issue was only about the map zooming and now this was fixed via https://github.com/graphhopper/graphhopper/pull/1868, thanks @twitwi!

**Closed by easbar** 2020-01-28 12:10 UTC
Labels: improvement, web
