### ISSUE TITLE
Bicycle/Bike routing over steps

### ISSUE THREAD

**Issue by neiljp** [graphhopper/graphhopper#390] opened 2015-04-02 14:24 UTC
Is this expected to be ok? What defines 'reasonable'? A certain count of steps? What if the number are known or not? 

eg 1) Route is taken up quite a substantial number of steps (no tag for it, but this is probably at least 2 storey's worth of steps, easily 20+):
http://www.openstreetmap.org/directions?engine=graphhopper_bicycle&route=57.14423%2C-2.09835%3B57.14295%2C-2.10240#map=18/57.14360/-2.10012

eg 2) Route is only a few steps - tagged as such - (though also goes down a footpath) but was the first case that triggered my thought in this direction:
http://www.openstreetmap.org/directions?engine=graphhopper_bicycle&route=57.16414%2C-2.10691%3B57.16580%2C-2.10230#map=17/57.16530/-2.10457

My feeling is that a small number would be reasonable to route over, in a 'dismount/lift' sense, but a sizeable distance (based on assumptions of steps per distance) or tagged explicitly should exclude (simplistic) or weight heavily against (ideally) a route. Perhaps an expression (equation) based on number of steps (exponential? power? polynomial?), or a base high weight but with a distance-scaling if untagged?

Disclaimer: I'm not a cyclist ;)

**Comment by neiljp** [comment] 2015-04-02 16:36
On graphhopper.com:
https://graphhopper.com/maps/?point=57.14404%2C-2.098024&point=Aberdeen%20Friends%20Meeting%20House%2C%20AB11%206HH%2C%20United%20Kingdom&vehicle=bike&locale=en-US&elevation=true&layer=Lyrk

Would be interesting to hear the ideas to explain what happens when the start point is moved slightly south, as the route changes dramatically to go through the shopping centre, out and round a lot.

**Comment by jansoe** [comment] 2015-04-02 16:55
> Would be interesting to hear the ideas to explain what happens when the start point is moved slightly south

There is the [pedestrian area north](http://www.openstreetmap.org/way/256787679)
and [the path south] http://www.openstreetmap.org/way/256787681

But even if those two objects are visual connected  by a dotted line, I can't find an element which actually connects them, i.e. [this node](http://www.openstreetmap.org/node/2624214475) is only connected to the path

**Comment by neiljp** [comment] 2015-04-02 17:13
It is true there is no connecting element; that is a current map bug I am working on. However, that does not explain to me why it doesn't route via guild st + steps like the original, rather than market/union.

**Comment by jansoe** [comment] 2015-04-02 17:25
as you have to go anyhow along junction market/guild, the [top route](https://graphhopper.com/maps/?point=57.143889%2C-2.097799&point=57.143679%2C-2.103989&vehicle=bike&locale=en-US&elevation=true&layer=MapQuest) it takes is a bit faster (even so 80m longer) than [the bottom route](https://graphhopper.com/maps/?point=57.143889%2C-2.097799&point=57.144901%2C-2.09694&point=57.143679%2C-2.103989&vehicle=bike&locale=en-US&elevation=true&layer=MapQuest). I think here it the "getting of bike" at the steps slows it too much down, whereas if you start north, the [detour to get to market street](https://graphhopper.com/maps/?point=57.144156%2C-2.098158&point=57.145463%2C-2.095723&point=57.143679%2C-2.103989&vehicle=bike&locale=en-US&elevation=true&layer=MapQuest) is way to long because of the oneways.

**Comment by neiljp** [comment] 2015-04-02 17:37
Well that maybe explains the jump and alternative route, but not why steps are included for bikes, except maybe small num_count where it's known.

**Comment by jansoe** [comment] 2015-04-02 17:43
> but not why steps are included for bikes, except maybe small num_count where it's known.

I mean that steps are allowed for routing is pretty easily explained, it is just enabled in the code (https://github.com/graphhopper/graphhopper/blob/908c23a0f977d5a1b75a3c88226c9438eba79fa8/core/src/main/java/com/graphhopper/routing/util/BikeFlagEncoder.java#L49)
But I agree that this is maybe not the best option and I like the idea to make it dependent on the number of steps. But it is hard to make a Bike Profile which suits all needs, i.e. sometimes taking steps can save you long detours.

**Comment by polarbearing** [comment] 2016-04-04 12:58
Supporting bicycle=dismount #695 (tagged 40000 times) would help to distinguish useful steps to route over.

**Comment by ratrun** [comment] 2017-01-06 18:23
This issue can be closed. Or?

**Comment by karussell** [comment] 2017-01-06 20:02
Due to #695 I would find it okay to close this. WTDY @neiljp ?

**Comment by neiljp** [comment] 2017-01-07 04:03
#695 is only explicit tagging of bicycle=dismount?

Case 1) now has a tag of 74 steps; for such large numbers of steps, surely this is relevant? Did I see that there is a run-time-adjustable encoder in the works? If so, then things like 'allow max steps' (or 'allow steps') could be used in that, for bike.

Case 2) hasn't changed, and neither has the directions for it on a bike (at least via osm): should it say, eg, "dismount for steps" even though there is no explicit dismount tag? Unless this is a mountain-bike encoder, perhaps?

**Comment by ratrun** [comment] 2017-01-07 09:55
@neiljp : Thank you! You are right. The online instance still shows the problem. Yesterday I tested it with my master, where both problems do not show up any longer. Currently I do not have an idea which of the commits did not find its way to the official master.

**Comment by ratrun** [comment] 2017-01-07 14:37
This is the test result with the current graphhopper master:
Case 1 does not route via the steps:
http://localhost:8989/?point=57.14423%2C-2.09835&point=57.14295%2C-2.10240&locale=de&vehicle=bike&weighting=fastest&elevation=true&key=&use_miles=false&layer=Omniscale&key=2a24e316-61ea-4850-b231-4ef2fe25d229

But case 2 does route via the steps:
http://localhost:8989/?point=57.16414%2C-2.10691&point=57.16580%2C-2.10230&locale=de&vehicle=bike&weighting=fastest&elevation=true&key=&use_miles=false&layer=Omniscale&key=2a24e316-61ea-4850-b231-4ef2fe25d229

The "graph.elevation.providers" setting does not influence the result:

**Comment by Locke** [comment] 2018-01-13 22:39
Just in case you need an additional example for the second case "Route is only a few steps": I tried to validate my mapping in a local park and noticed that a dismount + steps is suggested, although the other way a bit more east via the path with incline=up (indicated by my red drawing) should be preferred:

![screenshot from 2018-01-13 23-29-19_](https://user-images.githubusercontent.com/53905/34910664-4d171ecc-f8ba-11e7-91ba-c8776eb2e211.png)

https://graphhopper.com/maps/?point=50.026187%2C8.880558&point=50.02698%2C8.881009&locale=en-US&vehicle=bike&weighting=fastest&elevation=true&use_miles=false&layer=Lyrk


The interesting thing is that this eastern path, i.e. avoiding the steps, is suggested for foot routing:

![screenshot from 2018-01-13 23-36-22_](https://user-images.githubusercontent.com/53905/34910695-f1ac3918-f8ba-11e7-85a5-c0d0b36fd59e.png)

https://graphhopper.com/maps/?point=50.02556%2C8.881706&point=50.026787%2C8.881084&locale=en-US&vehicle=foot&weighting=fastest&elevation=true&use_miles=false&layer=Lyrk

**Comment by Klumbumbus** [comment] 2018-03-29 10:55
Here: https://www.openstreetmap.org/directions?engine=graphhopper_bicycle&route=51.13080%2C14.93865%3B51.12876%2C14.93490 it routes over a 224m long highway=steps while the alternative is not so much longer (504m). This doesn't look like a good routing.

**Comment by karussell** [comment] 2018-03-29 12:24
Interesting case. The problem is that most of the expected path is also on a very low speed of between 2 and 4km/h as you can see with the path details:

https://graphhopper.com/maps/?point=51.130205%2C14.938622&point=51.129573%2C14.937984&point=51.129845%2C14.937007&vehicle=bike&details=average_speed&debug=true&instructions=false

Maybe we once again have an elevation artifact here. One could extract the area from OSM and try locally to verify this.

**Comment by karussell** [comment] 2021-05-22 15:57
Will close this issue as the steps are in most cases now avoided and furthermore everyone can customize the bike profile to their needs (also on GraphHopper Maps). And so even for "extreme cases" you can exclude steps:

https://graphhopper.com/maps/?point=57.144168%2C-2.100551&point=57.143874%2C-2.101071&profile=bike&custom_model=%7B%22speed%22%3A%5B%7B%22if%22%3A%22road_class+=%3D+STEPS%22%2C%22multiply_by%22%3A0%7D%5D%7D

**Closed by karussell** 2021-05-22 15:57 UTC

**Comment by easbar** [comment] 2021-05-23 09:34
One thing to remember when avoiding steps, bridges, tunnels etc. is that the edge weights are all proportional to the distance of the edges. So using priority with `multiply_by: 0` works to exclude steps, but setting something like `multiply_by: 0.5` to 'somewhat avoid' steps won't work in most cases. For this we would rather need some fixed penalty value that is not multiplied with the distance. Let's see if such use-cases are required and if yes we might have to extend the custom_model.
