### ISSUE TITLE
Invalid routing choices for both pedestrian and biking

### ISSUE THREAD

**Issue by bagage** [graphhopper/graphhopper#1270] opened 2018-01-16 16:45 UTC
I'm getting an odd route choice when using GraphHopper, both on openstreetmap.org and graphhopper.com/maps (same results for both).

For pedestrian, an extra loop is added:
- [GraphHopper for pedestrian on openstreetmap.org](http://www.openstreetmap.org/directions?engine=graphhopper_foot&route=45.10281%2C5.01784%3B45.10385%2C5.01740#map=17/45.10321/5.01443)
- [GraphHopper for pedestrian on official website](https://graphhopper.com/maps/?point=45.10281%2C5.01784&point=45.10385%2C5.0174&locale=fr&vehicle=foot&weighting=fastest&elevation=true&use_miles=false&layer=Omniscale)
![image](https://user-images.githubusercontent.com/1451988/35000537-f69792b6-fae4-11e7-8ead-b74fad00b3f1.png)

For biking, another route choice but still not the expected one:
- [GraphHopper for biking on openstreetmap.org](http://www.openstreetmap.org/directions?engine=graphhopper_bicycle&route=45.10281%2C5.01784%3B45.10385%2C5.01740#map=17/45.10115/5.01975)
- [GraphHopper for biking on official website](https://graphhopper.com/maps/?point=45.10281%2C5.01784&point=45.10385%2C5.0174&locale=fr&vehicle=bike&weighting=fastest&elevation=true&use_miles=false&layer=Omniscale)
![image](https://user-images.githubusercontent.com/1451988/35000526-ef6fcd5a-fae4-11e7-9c15-9df25ede9705.png)

In the mean time the correct route choice is proposed on [mapcat.com](https://www.mapcat.com/directions/bicycle#map=19.2/45.10338/5.01719&route=45.10328,5.01749;45.10341,5.01745). 

![image](https://user-images.githubusercontent.com/1451988/35000516-e7ec7e7a-fae4-11e7-9204-35947360f04f.png)

I could not find anything obvious on OSM data but something must be wrong I guess?

**Comment by karussell** [comment] 2018-01-17 08:34
Oh, this looks really wrong.

**Comment by karussell** [comment] 2018-01-17 09:02
This is really strange and has nothing to do with elevation or with CH. Unfortunately I cannot reproduce this locally.

Somehow [south east way](https://www.openstreetmap.org/way/8585616) is connected to [north west way](https://www.openstreetmap.org/way/549172549) but not to [north east/south west way](https://www.openstreetmap.org/way/549172550) via [this node](https://www.openstreetmap.org/node/5304951140#map=19/45.10335/5.01742) - there is also no duplicate node or overlaying way. Also [west way](https://graphhopper.com/maps/?point=45.1036%2C5.017748&point=45.103426%2C5.016911&point=45.106137%2C5.015066&locale=en&vehicle=foot) is disconnected. [This route](https://graphhopper.com/maps/?point=45.1036%2C5.017748&point=45.103426%2C5.016911&point=45.106137%2C5.015066&vehicle=foot) sums it up IMO:

![route](https://user-images.githubusercontent.com/129644/35034147-7dcf259a-fb6d-11e7-8c24-6ec545ca0f70.png)

**Comment by karussell** [comment] 2018-01-17 09:13
Could it be that there was an issue that is now fixed? As the mentioned ways were all modified 2 days ago. Ok, let us wait a few hours until our most recent import process is done and then we'll see if it was fixed via fixing the data.

**Closed** 2018-01-17 20:28 UTC
Labels: bug
