### ISSUE TITLE
OSMreader parsing error

### ISSUE THREAD

**Issue by kshnkvn** [graphhopper/graphhopper#1908] opened 2020-02-13 12:10 UTC
Hello. I'll tried parse north-america-latest.osm.pbf, but all time i'll got the error:
```shell
ERROR [2020-02-13 00:06:49,447] com.graphhopper.reader.osm.OSMReader: Couldn't properly add edge with osm ids:[2310343336, 2342574566, 55740198, 55740198, 6771887975, 55694839, 2342574587, 7174921255, 55808824, 2342434446, 2342434379, 2342434408, 55808826, 2342434482, 2342434331, 55808829, 2342434348, 55808831, 2342434504, 55808834, 2342434308, 2342434374, 2342434398, 55808837, 55808841, 465186748, 55752281, 2342434497, 2342434319, 6772252654, 2342434341, 2342434400, 2342434421, 2342434364, 55808845, 55723554, 2342434313, 2342434322, 55808846, 2342434458, 55781872, 55808850, 55723547, 2342434472, 2342434370, 2342434477, 2342434381, 465186767, 55808853, 6954420471, 4003357373, 2342434399, 55808856, 2342434492, 2342434409, 55719184, 2342434501, 55808858, 2511053517, 55808861, 55719142, 55719121, 2342434356, 6801690171, 55808864]
! java.lang.ArrayIndexOutOfBoundsException: -12
! at com.graphhopper.storage.RAMDataAccess.getInt(RAMDataAccess.java:207)
! at com.graphhopper.reader.PillarInfo.getLatitude(PillarInfo.java:83)
! at com.graphhopper.reader.osm.OSMReader.handlePillarNode(OSMReader.java:768)
! at com.graphhopper.reader.osm.OSMReader.addOSMWay(OSMReader.java:659)
! at com.graphhopper.reader.osm.OSMReader.processWay(OSMReader.java:407)
! at com.graphhopper.reader.osm.OSMReader.writeOsm2Graph(OSMReader.java:271)
! at com.graphhopper.reader.osm.OSMReader.readGraph(OSMReader.java:145)
! at com.graphhopper.GraphHopper.importData(GraphHopper.java:692)
! at com.graphhopper.GraphHopper.process(GraphHopper.java:661)
! at com.graphhopper.GraphHopper.importOrLoad(GraphHopper.java:639)
! at com.graphhopper.http.GraphHopperManaged.start(GraphHopperManaged.java:71)
! at io.dropwizard.lifecycle.JettyManaged.doStart(JettyManaged.java:27)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
! at org.eclipse.jetty.server.Server.start(Server.java:419)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
! at org.eclipse.jetty.server.Server.doStart(Server.java:386)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
! at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:53)
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:44)
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
! at io.dropwizard.cli.Cli.run(Cli.java:78)
! at io.dropwizard.Application.run(Application.java:93)
! at com.graphhopper.http.GraphHopperApplication.main(GraphHopperApplication.java:33)
Exception in thread "PBF Reader" java.lang.RuntimeException: Unable to read PBF file.
        at com.graphhopper.reader.osm.pbf.PbfReader.run(PbfReader.java:50)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.lang.InterruptedException
        at com.graphhopper.reader.osm.OSMInputFile.process(OSMInputFile.java:253)
        at com.graphhopper.reader.osm.pbf.PbfDecoder.sendResultsToSink(PbfDecoder.java:96)
        at com.graphhopper.reader.osm.pbf.PbfDecoder.processBlobs(PbfDecoder.java:151)
        at com.graphhopper.reader.osm.pbf.PbfDecoder.run(PbfDecoder.java:162)
        at com.graphhopper.reader.osm.pbf.PbfReader.run(PbfReader.java:47)
        ... 1 more
Caused by: java.lang.InterruptedException
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
        at java.util.concurrent.LinkedBlockingQueue.put(LinkedBlockingQueue.java:350)
        at com.graphhopper.reader.osm.OSMInputFile.process(OSMInputFile.java:251)
        ... 5 more
INFO  [2020-02-13 00:06:49,472] org.eclipse.jetty.server.AbstractConnector: Started application@7e2c64{HTTP/1.1,[http/1.1]}{0.0.0.0:8989}
INFO  [2020-02-13 00:06:49,480] org.eclipse.jetty.server.AbstractConnector: Started admin@7c1e32c9{HTTP/1.1,[http/1.1]}{localhost:8990}
ERROR [2020-02-13 00:06:49,480] io.dropwizard.cli.ServerCommand: Unable to start server, shutting down
! java.lang.ArrayIndexOutOfBoundsException: -12
! at com.graphhopper.storage.RAMDataAccess.getInt(RAMDataAccess.java:207)
! at com.graphhopper.reader.PillarInfo.getLatitude(PillarInfo.java:83)
! at com.graphhopper.reader.osm.OSMReader.handlePillarNode(OSMReader.java:768)
! at com.graphhopper.reader.osm.OSMReader.addOSMWay(OSMReader.java:659)
! at com.graphhopper.reader.osm.OSMReader.processWay(OSMReader.java:407)
! at com.graphhopper.reader.osm.OSMReader.writeOsm2Graph(OSMReader.java:271)
! ... 19 common frames omitted
! Causing: java.lang.RuntimeException: Couldn't process file /data/north-america-latest.osm.pbf, error: -12
! at com.graphhopper.reader.osm.OSMReader.writeOsm2Graph(OSMReader.java:295)
! at com.graphhopper.reader.osm.OSMReader.readGraph(OSMReader.java:145)
! at com.graphhopper.GraphHopper.importData(GraphHopper.java:692)
! at com.graphhopper.GraphHopper.process(GraphHopper.java:661)
! at com.graphhopper.GraphHopper.importOrLoad(GraphHopper.java:639)
! at com.graphhopper.http.GraphHopperManaged.start(GraphHopperManaged.java:71)
! at io.dropwizard.lifecycle.JettyManaged.doStart(JettyManaged.java:27)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
! at org.eclipse.jetty.server.Server.start(Server.java:419)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
! at org.eclipse.jetty.server.Server.doStart(Server.java:386)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
! at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:53)
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:44)
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
! at io.dropwizard.cli.Cli.run(Cli.java:78)
! at io.dropwizard.Application.run(Application.java:93)
! at com.graphhopper.http.GraphHopperApplication.main(GraphHopperApplication.java:33)
INFO  [2020-02-13 00:06:49,492] org.eclipse.jetty.server.AbstractConnector: Stopped application@7e2c64{HTTP/1.1,[http/1.1]}{0.0.0.0:8989}
INFO  [2020-02-13 00:06:49,496] org.eclipse.jetty.server.AbstractConnector: Stopped admin@7c1e32c9{HTTP/1.1,[http/1.1]}{localhost:8990}
java.lang.RuntimeException: Couldn't process file /data/north-america-latest.osm.pbf, error: -12
        at com.graphhopper.reader.osm.OSMReader.writeOsm2Graph(OSMReader.java:295)
        at com.graphhopper.reader.osm.OSMReader.readGraph(OSMReader.java:145)
        at com.graphhopper.GraphHopper.importData(GraphHopper.java:692)
        at com.graphhopper.GraphHopper.process(GraphHopper.java:661)
        at com.graphhopper.GraphHopper.importOrLoad(GraphHopper.java:639)
        at com.graphhopper.http.GraphHopperManaged.start(GraphHopperManaged.java:71)
        at io.dropwizard.lifecycle.JettyManaged.doStart(JettyManaged.java:27)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
        at org.eclipse.jetty.server.Server.start(Server.java:419)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
        at org.eclipse.jetty.server.Server.doStart(Server.java:386)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:53)
        at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:44)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
        at io.dropwizard.cli.Cli.run(Cli.java:78)
        at io.dropwizard.Application.run(Application.java:93)
        at com.graphhopper.http.GraphHopperApplication.main(GraphHopperApplication.java:33)
Caused by: java.lang.ArrayIndexOutOfBoundsException: -12
        at com.graphhopper.storage.RAMDataAccess.getInt(RAMDataAccess.java:207)
        at com.graphhopper.reader.PillarInfo.getLatitude(PillarInfo.java:83)
        at com.graphhopper.reader.osm.OSMReader.handlePillarNode(OSMReader.java:768)
        at com.graphhopper.reader.osm.OSMReader.addOSMWay(OSMReader.java:659)
        at com.graphhopper.reader.osm.OSMReader.processWay(OSMReader.java:407)
        at com.graphhopper.reader.osm.OSMReader.writeOsm2Graph(OSMReader.java:271)
        ... 19 more
```

**Comment by karussell** [comment] 2020-02-17 17:09
What GraphHopper version are you using? Do you have a minimal pbf file and the config.yml that reproduce this error?

**Comment by karussell** [comment] 2020-04-17 17:34
No feedback since several months, so closing for now as it could be an old bug that is already fixed. And have never spotted something like this since months in production.

**Closed by karussell** 2020-04-17 17:34 UTC
