### ISSUE TITLE
Kink-y routing for highway=pedestrian areas

### ISSUE THREAD

**Issue by jengelh** [graphhopper/graphhopper#1791] opened 2019-11-13 00:30 UTC
**Case 1.**

https://osm.org/directions?engine=graphhopper_foot&route=51.53301%2C9.93450%3B51.53384%2C9.93674

![obs](https://user-images.githubusercontent.com/8861948/68721952-55cd6e00-05b4-11ea-9fd5-8a6a92a0d127.png)

Observed: GH proposed route (blue line), approximately 231m
Expected: the shorter route (black line), approximately 219m

**Case 2.**

https://osm.org/directions?engine=graphhopper_bicycle&route=51.55629%2C9.94831%3B51.55589%2C9.94655#map=19/51.55596/9.94737

![obs2](https://user-images.githubusercontent.com/8861948/68722127-d55b3d00-05b4-11ea-9961-1ae337a13a09.png)

Observed: overshoots and does a u-turn
Expected: probably should ignore ways having both {highway=pedestrian,area=yes} for bike routing entirely

**Comment by boldtrn** [comment] 2019-11-13 07:34
That's probably a duplicate of: https://github.com/graphhopper/graphhopper/issues/82

**Comment by karussell** [comment] 2019-11-13 08:41
Yes.

> Expected: probably should ignore ways having both {highway=pedestrian,area=yes} for bike routing entirely

It cannot ignore them always as getting off the bike is sometimes faster than a lengthy detour.

**Closed by karussell** 2019-11-13 08:41 UTC
