### ISSUE TITLE
OSM Reader optimization

### ISSUE THREAD

**Issue by NopMap** [graphhopper/graphhopper#69] opened 2013-06-07 06:59 UTC
I started this issue to collect our ideas for making the reader more memory efficient and/or faster (once we hit the physical memory limit this is about the same).

(1) Provide multithreaded processing for OSM XML-Files to process the planet file in .osm.bz2 format. Usage of two CPUs is possible, but not more due to the nature of the SAX parser. (PBF files are already processed on multiples CPUs).

(2) I noted that node information is shifted from pillarnodes to towernodes and the towernodes array is still growing with redundant data during pass2. This is not necessary and should be avoided with a different data layout.

**Comment by git2dinu** [comment] 2015-11-08 11:54
@karussell Still OSM reader opimization issue is open state ?

**Comment by git2dinu** [comment] 2015-11-08 11:54
@karussell  how to optimize the OSM reader in graphhopper ?

**Comment by karussell** [comment] 2015-11-08 12:14
Ymall improvements should still be possible but I doubt it is worth the effort. What issues are you experiencing?

**Comment by boldtrn** [comment] 2017-02-14 05:11
@karussell I would think that (3) could be worth the effort, don't you think? It should be possible to do this rather fast, but this might reduce the number of visited nodes per request? Did you run any numbers on this? 

*EDIT:*

OK, I was curious and hacked something rather fast and ugly, so I would think it might contain one or the other bug, but still the numbers look interesting. I tried it for car and Baden-Württemberg.

The file I used contains 1 646 987 edges (not the latest, maybe a month or two old).
According to my fast hack, we could remove 90 666 edges, which is more than 5%. So the routing could become about 5% faster, for the flexible mode, if I am not completely mistaken.

See this commit: https://github.com/boldtrn/graphhopper/commit/362bea4d015b9973f17aae920f45a30a205be6b2

Might contain massive bugs :) Let me know.

*EDIT2:*

Autralia with 2 153 920 edges, found 74 914 removable edges. Not that much in Australia.

**Comment by karussell** [comment] 2017-02-14 12:23
Thanks & Interesting. As this is not that much for Australia, I'll run the code for world wide and we decide based on that?

**Comment by boldtrn** [comment] 2017-02-14 20:52
> Thanks & Interesting. As this is not that much for Australia, I'll run the code for world wide and we decide based on that?

Sounds good.

**Comment by boldtrn** [comment] 2017-02-18 12:12
I just tested this for the planet

There are 7 284 249 removeable edges. The planet has 175 597 863. So it's roughly 4%. I tested this for car, I would assume the number for bike and foot would be a lot higher. There are less tags on foot ways (AFAIK), so the chance that they are similar is higher, I guess. I will just run another import with bike.

**Comment by karussell** [comment] 2017-02-18 17:05
Thanks :+1: ! If it is just 4% then it would make sense only if we can implement it rather flawlessly somehow.

**Comment by boldtrn** [comment] 2017-02-19 01:01
Ok, so I just tested it with bike.

There are 7 662 735 removeable edges. The planet has 208 316 598 edges. So it is even a bit less for bike.

> If it is just 4% then it would make sense only if we can implement it rather flawlessly somehow.

What do you mean with that?

Analyzing the graph is quite fast. Shouldn't take longer than a couple of minutes for planet. 

I am not sure about the impact of this change. What happens if we merge edges? Could this create an issue for the Lookup, as we only match the whole edge?

**Comment by karussell** [comment] 2017-02-19 18:50
The problem is that removing edges or nodes is not really possible (at the moment). We could only mark nodes and then they will be removed on graph.optimize (but not the edges). So we should make this feature optional and use this only when graph.sorted is enabled where we copy the graphs and indirectly remove the nodes and edges this way.

**Comment by boldtrn** [comment] 2017-02-20 00:26
> The problem is that removing edges or nodes is not really possible (at the moment). We could only mark nodes and then they will be removed on graph.optimize (but not the edges).

I see. Wasn't sure if this is possible. Ok then it might be as useful as I thought. Should we still do this?

**Comment by karussell** [comment] 2017-02-20 09:27
I would postpone it for now, maybe we should reconsider when we want to 'compress' stuff a bit more.

**Comment by karussell** [comment] 2021-07-22 06:57
> Put all node information in the same data structure, mark pillar/tower nodes with a flag and seperate them in a postprocessing step.

I think we need to make OSMReader simpler & better customizable (see https://github.com/graphhopper/graphhopper/pull/2193#issuecomment-777356336) and this proposal here would make it IMO harder as IDs would need to tweaked. I am not sure if this saves memory at all or if it would be faster. So closing here.

**Closed by karussell** 2021-07-22 06:57 UTC
Labels: improvement
