### ISSUE TITLE
graphhopper process stuck at 100% CPU, requires kill -9

### ISSUE THREAD

**Issue by kingcu** [graphhopper/graphhopper#304] opened 2015-01-17 17:52 UTC
Every couple weeks, the graphhopper process will end up maxing out all cores and spiking load average. It requires a kill -9

Currently deployed 22466f0c81113479c78d185a100f356fc1623b43 but has happened with previous versions back to beginning of December.

Here's a screenshot of the strace, process stuck in futex:

https://www.dropbox.com/s/gquxt1d1d1awdry/Screenshot%202015-01-17%2009.39.04.png?dl=0

Since this happens on occasion, is there anything helpful i can do to help troubleshoot while it's happening? I am running redundant servers, so having one offline for a few isn't the end of the world.

**Comment by NopMap** [comment] 2015-01-17 18:05
I have a problem that might be related. Occasionally, the GH process will max CPU load until killed.

I suspect that the routing somehow gets into an endless loop.

I observed that this occurred only very rarely in the beginning (about once every 3 months) and became more frequent over time. As I did not update the code, I think the cause must be somewhere in the data. I am using my own Encoders and bidirectional weights, so the problem might not be in GHs standard code.

I never got around to debugging the actual cause and just added a watchdog to automatically reset the server when this happens.

Are you using standard Encoders and import procedure or do you have a custom one? What vehicles do you have?

**Comment by kingcu** [comment] 2015-01-17 18:07
Using graphhopper straight out of the box for bike, car and foot routing. I
can expect it to happen once every two or three weeks, planning on also
auto killing server when it maxes out.

**Comment by karussell** [comment] 2015-01-17 22:10
Hi, please describe your configs in detail. As well as the used area und JVM settings. Of course, the best would be to have it reproducable.

Do you import from OSM and run routes directly afterwards? There is a JVM bug which might then be the reason. (search for it in the issues+try the first workaround)

**Comment by karussell** [comment] 2015-01-18 14:10
See #187 where the workaround could be: try in your JAVA_OPST `-XX:CompileCommand=exclude,com.graphhopper.coll.GHLongIntBTree::put'

**Comment by kingcu** [comment] 2015-01-20 19:07
From reading that issue, it sounds like it might not be the same. I first run an import which takes upwards of 2 hours. I then restart graphhopper using the shell script like so:

`./graphhopper.sh web planet.osm.pbf`

The issue mentions the problem is on import, not while running the web service. Or am I reading it wrong?

**Comment by karussell** [comment] 2015-01-20 19:52
Yes, then it is different. But still I need your config.properties and ..

> as well as the used area und JVM settings. Of course, the best would be to have it reproducable

Additionally if it is not reproducable: can you hook into the system when it has the problem with a profiler (yourkit, netbeans or eclipse etc)?

**Comment by kingcu** [comment] 2015-01-20 20:28
Here's a gist for my [config.properties](https://gist.github.com/kingcu/b0d454029f8f79097ff8)

JAVA_OPTS are  `-XX:PermSize=200m -XX:MaxPermSize=200m -Xmx40000m -Xms40000m`

Just chatted with a java dev friend of mine and got some tips on troubleshooting, so I'll provide a bit more detail if/when it happens again.

**Comment by karussell** [comment] 2015-01-20 20:33
Thanks! What is your area? whole world? europe? city? 

As it could be related to #104 although you have plenty of RAM. Still only a couple of queries could take lots of RAM and could bring your Garbage collector + CPU down. So, if the area is bigger than a city you should limit the distance of the routes for the "none-CH" mode and/or have this feature fixed.

**Comment by kingcu** [comment] 2015-01-20 20:40
Running with the entire world, so that's definitely a good theory. going to experiment a bit and see if I can reproduce. Just got some good tips on JVM garbage collection issues, troubleshooting etc so we'll see! Experimenting with PrintGC, PrintGCDetails and PrintGCTimeStamps to see if I can get better insight into whether this is a GC issue or not.

**Comment by karussell** [comment] 2015-01-20 21:40
Yes. Could be a GC issue too. Also you can try to move to JDK 8 with better default GC IMO

**Comment by karussell** [comment] 2015-02-23 14:13
@kingcu any news on this? Were you able to fix it?

**Comment by kingcu** [comment] 2015-02-23 18:06
it hasn't come back up yet, but i have garbage collection logging setup and
a plan to do a bit more digging if it comes back. thanks for checking back
in

**Comment by kingcu** [comment] 2015-04-01 15:46
I had this happen again last night. It happened when I took one of our two servers out of production (relying on only one), so the load went up. Though we don't currently have high utilization of this service (maybe bursts of 5-10 requests per second here/there, but nothing too high and nothing sustained), so not sure if that's the problem. Here's an excerpt from the log showing where the problem first happens:

https://gist.github.com/kingcu/fb115f358ef5d5006b3e

The garbage collection log doesn't seem to have any entries that correspond to the issue. It seems like when I kill -9'd the process, the logfile was truncated and started over.

However, on the logfile from the previous day, I did see a troubling full garbage collection entry, here's an excerpt, notice the last line and how long spent in user time:

https://gist.github.com/kingcu/d8f77743d807ecede3a0

**Comment by karussell** [comment] 2015-04-01 16:08
With 'it happen again' you mean the process get stuck at 100% which requires you to kill it?

To make sure that this is not just a GC configuration problem I recommend using Java 8 as the default garbage collector has improved or using a different garbage collection mode for java 7 (I think it was concurrent gc) which avoid such long full gc times.

**Comment by kingcu** [comment] 2015-04-01 16:49
Yeah just installed Java 8 and will see if that solves it. Yes, stuck at
100% CPU requiring a kill -9 to solve.

**Comment by kingcu** [comment] 2015-04-01 17:17
Even if a new JDK fixes the problem, isn't there an issue with how
graphhopper handles running out of memory? I would think the proper action
would be to let the JVM die. I run everything under monit so it would just
come back up. No need to destroy the server by pegging the CPU.

Going to add a monit rule to restart graphhopper if it gets stuck at full
utilization again, though for an OoM graphhopper should just die on its own.

**Comment by karussell** [comment] 2015-04-01 17:24
There is no mechanism in GraphHopper to 'keep running' even if errors - we try hard to avoid this.

But in this case this is more a jetty related thing, which we need to look up on how to 'really die' for such errors.

**Comment by karussell** [comment] 2016-04-21 19:49
I have researched the topic a bit and the JVM does only end the thread where the OOM was thrown! All other threads keep running which makes partly sense as the hope is that killing the one thread freed RAM.

In order to exit the JVM on any OOM you can use the following option (currently untested from me):
`-XX:OnOutOfMemoryError="kill -9 $PPID"` or `-XX:OnOutOfMemoryError="kill -9 %p"`

Also to investigate the problem attach `-XX:+HeapDumpOnOutOfMemoryError`

So the problem here could be that there was too few RAM and the GC did its work but too heavy or with very slow progress or something and too many threads existed, that all should have been killed. To analyze this in the future we add this flag now by default: https://github.com/graphhopper/graphhopper/commit/e7804a641356d9c6c0fafa68bfdf2a5774363b9f

I'm closing this for now - if anything similar happens again: please report it with the heap dump, GH&java&OS version as well as a potential log file and GC log (via `-verbose:gc`).

**Closed by karussell** 2016-04-21 19:49 UTC

**Comment by karussell** [comment] 2016-06-06 11:18
The new option `-XX:+HeapDumpOnOutOfMemoryError` is a bit ugly if using this for bigger instances as they'll write GBs to the disc potentially filling your (rather smallish) SSD. Will still keep it for now.

**Comment by karussell** [comment] 2016-06-07 13:22
Will remove the option by default to avoid this issue. What we need is a killing script if an OOM occurs. Then the user will notice that something went wrong and the JVM won't continue and creating lots of such file
