### ISSUE TITLE
Instructions: Add U-Turn Instruction

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper#1064] opened 2017-05-15 02:08 UTC
Currently there is no u-turn instruction for GraphHopper. 

There are two types of u-turns:
1: Being on a big road with separated lanes, e.g. https://graphhopper.com/maps/?point=52.508875%2C13.326448&point=52.50896%2C13.326555
2: Being on a normal road. This usually happens when there is a via point on that road or when navigating and taking a wrong turn, e.g. https://graphhopper.com/maps/?point=52.97255%2C12.879045&point=52.975069%2C12.881727&point=52.972576%2C12.879045

Handling case 1 won't be too easy and would probably require #1007.
Handling case 2 should be doable with checking the orientation and/or checking if the prev edge id is equal to the next edge id.

So this issue is about adding U-Turn instructions at all and provide them for case 2.

**Comment by devemux86** [comment] 2017-05-15 05:56
Is 1st case related to multiple ways turn restriction #446?
Or else we could have false u-turns.

**Comment by boldtrn** [comment] 2017-05-27 05:36
> Is 1st case related to multiple ways turn restriction #446?

Yes, exactly. Currently, there is no solution for this. So I was planning on solving case 2 only for now. Case 1 needs more thinking I guess.

**Comment by karussell** [comment] 2017-05-27 11:05
I think the 2nd is a duplicate of #289

**Comment by boldtrn** [comment] 2017-05-29 06:40
> I think the 2nd is a duplicate of #289

Yes you are right, sorry didn't found that.

**Closed** 2017-12-13 09:38 UTC
Labels: improvement
