### ISSUE TITLE
unnecessary detour over motorway_link

### ISSUE THREAD

**Issue by AllroadsNL** [graphhopper/graphhopper#2080] opened 2020-07-06 15:32 UTC
[Situation link OSM site](https://www.openstreetmap.org/directions?engine=graphhopper_car&route=52.6748%2C5.7221%3B52.6893%2C5.7577#map=15/52.6804/5.7569)
[Situation link Graphhopper site](https://graphhopper.com/maps/?point=52.678269%2C5.730207&point=52.688506%2C5.755398&locale=nl-NL&vehicle=car&weighting=fastest&turn_costs=true&use_miles=false&layer=Omniscale)

Image situation:

![Dtour motorway junction](https://user-images.githubusercontent.com/8817345/86605216-b0359780-bfa6-11ea-85aa-b1d5bc641914.JPG)

Espected:
That the motorway was taken straight on.

Failure:
The D tour is taken over the motorway_link.

Data is changed recently because of Government maxspeed rules on motorway. (nation wide)
motorway:
maxspeed=100 maxspeed:conditional=130 @ (19:00-06:00)

But on the motorway_link to the motorway  [situation streetview](https://www.google.nl/maps/@52.6828673,5.7426369,3a,75y,58.98h,85.5t/data=!3m6!1e1!3m4!1sW1wyZpWCd4n2l1WnIHN7cA!2e0!7i13312!8i6656) there is this  G01 trafficsign

![NLG01](https://user-images.githubusercontent.com/8817345/86606805-c3e1fd80-bfa8-11ea-94fe-7ace37b9c256.gif)

This means from that point,[ rules says you can drive 130](https://wiki.openstreetmap.org/wiki/NL:Overzicht_Nederlandse_Verkeersborden#G:_Verkeersregels). And Government did not adjust that,
Once directly on the motorway, we get mostly a trafficsign with maxspeed=100 maxspeed:conditional=130 @ (19:00-06:00), because there is a other junction comming up, in this case, there is only a maxspeed=100 sign.
[Stituation streetview](https://www.mapillary.com/map/im/LQJ7g-DB4tbbFM9dCjx3GA).

Maybe for this type of situations, with a motorway_link. where the maxspeed is higher as the motorway, where a D tour is visualised wrongly a other time/speed calculation should be used?

There is also highway=give_way on the exit motorway_link, that does not have the effect as it should have. To better calculate the time/speed ratio?

General:
At a give_way, people come mostly to a stop, so this effect the time/speed ratio.
At a entrance motorway_link, people have to accelarate mostly, this should effect the time/speed ratio. 

Or is the program struggling with the  conditional settings?

![Dtour motorway junctionJOSM](https://user-images.githubusercontent.com/8817345/86609177-dad61f00-bfab-11ea-9f78-6807b2cd992b.JPG)

The data in OSM is correct, a situation, that now is common in the Netherlands. 
The Government, says, because of the entrence of a motorway, people mostly drive/ride not that 130 maxspeed, must accelerate, because it is a entrance. More trafficsigns, does not make the road safer. After a cpuple of hunderd meters they get the new maxspeed sign.
It is a consideration of more trafficsigns, costs and safety risks.

**Comment by karussell** [comment] 2020-07-06 15:57
Interesting case.

> Or is the program struggling with the conditional settings?

It is ignored at the moment. See OSMMaxSpeedParser.

> At a give_way, people come mostly to a stop, so this effect the time/speed ratio.

We indeed currently do not take into account these node infos, but we should :) Like we do consider barriers and convert them into tiny edges with certain edge access properties.

One temporal workaround could be to use the (rejected) maxspeed:practical tag: https://wiki.openstreetmap.org/wiki/Proposed_features/Practical_maxspeed

**Comment by AllroadsNL** [comment] 2020-07-06 18:41
A motorway_link, in general is a part of the road system, where you accelerate to merge in to the motorway or exit decelerate.
Although a motoway_link has a maxspeed tag, we have to take in mind the acceleration/decellerate proces as a part of the traffic behaviour.

Acceleration, means, a average speed on that part of the road.

Adding some time/cost to the motorway link, could be a good idea, mostly these roads are curved, merge/exit behaviours, from other roads.

Sometimes **extra** speed traffic signs with a low speed. say 70 or less are placed. For saftey reasons.
Normally, then above 70, a time/cost must be taken in account. to level out the accelerate/decelerate.

Average, can not be expressed by a maxspeed:pratical tag, such tags is for the whole road, on every part you can drive/ride.
There is not a Government maxspeed advised sign.

**Comment by karussell** [comment] 2020-09-30 11:32
I have a prototype that scans the neighboring edges of all these "links" and reduces the speed of these "links" to the maximum value of the adjacent edges (multiplied by a factor that is default 1 for non-motor vehicles and 0.85 for motor vehicles): https://github.com/graphhopper/graphhopper/compare/road_class_link

This way the acceleration is considered and these links should no longer be selected for a route. I have to do some quality and performance tests before we can consider this in the master branch.

**Comment by karussell** [comment] 2020-10-01 13:27
Hmmh, the problem is that this does not happen with the open source version as the speed estimates are solely based on road classes and so link is always slower than the main road class and in theory it is not an issue here and nothing needs to be fixed ;) . So I'll try to fix this in our downstream code and if done close here.

Maybe if I find time I can try to make some code that improves the ETAs open and use the opportunity to re-implement some parts of it. This way the community could also fine-tune it for the different areas of the world. But this is a bigger effort ...

**Comment by traut21** [comment] 2020-10-23 12:16
The problem does not appear if an actual 70 speed limit was given - but that's not necessarily the case. The problem here is the missing limit.

I agree with option one, a maxspeed practical. I would not add limits which actually are not there

However, there is a more practical solution, adding more details to the exits: Usually the end-of-highway sign appears about 150 m before the crossing, then a give-way-of-right is there. The entry line usually has the way of right and begins about 100 to 150 m after the crossing with the highway sign.

So adding more OSM details will prevent incorrrect routing because the speed limit in between would be 80.

**Comment by AllroadsNL** [comment] 2020-10-23 13:46
> The problem here is the missing limit.

All maxspeed limits are there.

The above case give now good routing, with the topic start links.

In the above case on the exit, it is 38 meter more 80 km/h where, now a maxspeed=100 is tagged. [ST view](https://www.google.nl/maps/@52.68257,5.7419373,3a,75y,68.27h,74.66t/data=!3m6!1e1!3m4!1sjsDa0e0m6d8GDsVEjfxxnw!2e0!7i13312!8i6656)
On the entrance it is 26 meter more 80 km/h, where now maxspeed=130 is tagged.
Totally 64 meter different km/h.

There is a part of 80 on the junction in the above case, now. Between secondary lanes


> So adding more OSM details will prevent incorrrect routing because the speed limit in between would be 80.

The problem, people, maybe a judge, because of the general feeling explaining the law, the intention of the law, that on junction  the speed is from the junction (node) till the sign the speed on the sign.Also when the sign is 0-50 meter away. (practical place)
On that part  (64 meter, case) nobody get a speed ticket, so that is not brought to court, eventually to the high court. Not knowing what a judge would decided.

At the end, it also the judge who decide how we must understand the law.

There (general) taggers and to the point taggers. It is about the feeling what they think is okay, is that the majority(?) And does a judge see it this way. How should we tag. Or to the point because of routing.

That is the dertermination to make.

And adapt the routing system.

give_way helps, also.

This ticket could be closed because of the example, but probably there are more examples like this with just a little different tagging,  just a few more meters and the routing is different.

**Comment by karussell** [comment] 2020-10-23 14:10
Yes, indeed, the routing should be fixed now. Thanks for reporting.

As stated before we adjust the speed a bit for more realistic values and had to do more fine tuning (see the branch for the actual fix).

> just a few more meters and the routing is different.

This is not expected and would be a bug.

**Closed by karussell** 2020-10-23 14:10 UTC

**Comment by traut21** [comment] 2020-10-23 15:17
The routing problem was fixed because I had added a 100 km/h speed limit. But I learned by now that this limit was inappropriate. The legal speed is 130 km/h, on the entry line, until you pass the first new 100 km/h sign which should have been added at every entry by now.

**Comment by karussell** [comment] 2020-10-23 16:14
The problem is now fixed on the software-side too. See e.g. also:

 - https://graphhopper.com/maps/?point=52.678269%2C5.730207&point=52.688506%2C5.755398
 - https://graphhopper.com/maps/?point=49.154787%2C8.564261&point=49.138958%2C8.554337
 - https://graphhopper.com/maps/?point=49.41477%2C8.547868&point=49.403814%2C8.545475

**Comment by AllroadsNL** [comment] 2020-10-23 19:08
> The routing problem was fixed because I had added a 100 km/h speed limit.

[This case is about this road entry line](http://osm.mapki.com/history/way.php?id=6519631) since 2016-02-10 there is a maxspeed on it. I did not see you as author.

[The exit](http://osm.mapki.com/history/way.php?id=6520282)2016-02-10

> the software-side too

This topic case, only.

**Comment by AllroadsNL** [comment] 2020-10-23 19:30
> As stated before we adjust the speed a bit for more realistic values and had to do more fine tuning (see the branch for the actual fix).

Thanks.
