### ISSUE TITLE
Route: More info for "Connections between locations not found"

### ISSUE THREAD

**Issue by michaelkrog** [graphhopper/graphhopper#581] opened 2015-11-27 20:34 UTC
If I make a route between many points but one of them are not possible to make a route to, then I get a RuntimeException with the message "Connections between locations not found" from https://github.com/graphhopper/graphhopper/blob/9d07f4fb300726aa2386587fbd52408b0fbdccbb/core/src/main/java/com/graphhopper/util/PathMerger.java#L142.

I miss some info about the actual point(s) that causes the error, so Im able to fix the data if that is the problem.

**Comment by karussell** [comment] 2015-11-27 21:00
Indeed this should be improved!

**Comment by karussell** [comment] 2016-09-17 10:30
Related to #776

**Comment by theaaron123** [comment] 2017-05-28 17:37
Has this been resolved [here](https://github.com/graphhopper/graphhopper/blob/826342c3b42b1f6402367e9aceb1cd7816a4f6c4/core/src/main/java/com/graphhopper/util/PathMerger.java#L131)?

**Comment by karussell** [comment] 2017-05-29 08:49
No, still the points are missing. BTW: @michaelkrog are you interested in the point index or actual lat,lon?

**Comment by oschlueter** [comment] 2017-10-05 22:24
Which points should be included in that collection? 

Say we have a graph like this:
```
a <--> b

       c <--> d
```
Further assume we'd like to travel from point `a` to point `d`, hence the problem is not a single node unconnected to the rest but a fifty-fifty split situation. 

The `Path` instance passed to `PathMerger.doWork` doesn't seem to contain any information regarding any specific points which are causing the error. Additionally it seems to me `fromNode` and `endNode` are set to `-1` if no path is found which would render calculations after the fact impossible. 

Thus would you have all points of the underlying graph be added to the collection?

**Comment by boldtrn** [comment] 2017-10-05 22:42
> The Path instance passed to PathMerger.doWork doesn't seem to contain any information regarding any specific points which are causing the error. Additionally it seems to me fromNode and endNode are set to -1 if no path is found which would render calculations after the fact impossible.

I haven't debugged this, but I would assume that you know for which of the paths you cannot find a connection.

Assume we want to find a way from Berlin via Cologne to Munich. GraphHopper would calculate two paths Berlin->Cologne and Cologne->Munich. If we see that the Path Cologne->Munich is empty, then we should be able to create an exception stating from point 1 to point 2.

**Comment by karussell** [comment] 2022-01-16 12:06
This is fixed now.

**Closed by karussell** 2022-01-16 12:06 UTC
Labels: improvement, good first issue
