### ISSUE TITLE
route description should mention if it goes through a ferry

### ISSUE THREAD

**Issue by yehoshuas** [graphhopper/graphhopper#794] opened 2016-09-14 14:26 UTC
here is an example:

https://graphhopper.com/maps/?point=41.022919%2C29.042176&point=41.024551%2C28.979297&locale=en-US&vehicle=foot&weighting=fastest&elevation=true&use_miles=false&layer=Omniscale

**Comment by karussell** [comment] 2016-09-14 14:30
duplicate of #455

**Closed by karussell** 2016-09-14 14:30 UTC

**Comment by yehoshuas** [comment] 2016-09-14 16:08
I went over issue #455, if I understood correctly, the reason you do not mention ferries is because there can be very short ferries.
This is not the issue in the example I gave, also notice that google maps does show the ferry in the instructions as expected:
https://www.google.com/maps/dir/41.022919,29.042176/'41.024551,28.979297'/@41.0218839,28.9721864,13z/data=!3m1!4b1!4m7!4m6!1m0!1m3!2m2!1d28.979297!2d41.024551!3e2

**Comment by karussell** [comment] 2016-09-14 16:14
We just do not include such an announcement **yet**, but we would like to in the future. Maybe you contribute a PR :) ?
