### ISSUE TITLE
The OSM file could not be loaded

### ISSUE THREAD

**Issue by suixing0591** [graphhopper/graphhopper#2506] opened 2022-01-05 04:49 UTC
When I use some OSM file in Java，A running error occurred；The error message is “va.lang.IllegalStateException: Suspicious coordinates for node 194623: (33.9399192,115.9891583) vs. (33.9395811,115.9936294,NaN)”；What is the reason？Looking forward to your reply！

**Comment by easbar** [comment] 2022-01-05 07:56
Which OSM file were you using? Which version of GraphHopper and what config file?

**Comment by suixing0591** [comment] 2022-01-06 00:59
![image](https://user-images.githubusercontent.com/66464220/148310974-19b8deca-b2c3-4c2e-8dea-3c31ffad7d13.png)
![image](https://user-images.githubusercontent.com/66464220/148311069-f97ac8ee-cbcb-4f4b-b13a-e5f6e3b38001.png)
![image](https://user-images.githubusercontent.com/66464220/148311184-f6d57d04-452d-40d0-940f-e703d5c0e77a.png)

**Comment by easbar** [comment] 2022-01-06 09:07
I think we saw this before for extracts from openstreetmap.fr: https://discuss.graphhopper.com/t/import-europe-web-jar-4-0/6919
I will try to reproduce this. In the meantime can you try the China extract from Geofabrik: https://download.geofabrik.de/asia/china-latest.osm.pbf

**Comment by easbar** [comment] 2022-01-06 17:33
Using this map:

![image](https://user-images.githubusercontent.com/17603532/148425493-e68d6872-f1a5-4788-9695-2618bdbe70e1.png)

I can reproduce your error for 4.0, but not for recent master. Can you confirm this?

**Comment by suixing0591** [comment] 2022-01-07 02:12
My problem using the new OSM has been solved. Thank you very much for your help!

**Comment by easbar** [comment] 2022-01-10 20:13
Closing here as this seems to be fixed in master and no need to backportas long as it only happens for certain extracts.

**Closed by easbar** 2022-01-10 20:13 UTC
