### ISSUE TITLE
Include elevation for foot/hiking profile

### ISSUE THREAD

**Issue by easbar** [graphhopper/graphhopper#1679] opened 2019-08-02 18:06 UTC
The German Alpine Club suggests a formula how elevation affects walking speed, as discussed here: https://discuss.graphhopper.com/t/walking-duration-estimate-elevation-ignored/4621/4

Related: #1597

**Comment by hungerburg** [comment] 2020-11-24 11:26
You might want to reopen this, the calculation is wrong, it gives the same result, whatever the direction. Sample paths:

- https://graphhopper.com/maps/?point=47.312133%2C11.383832&point=47.29842%2C11.391975&point=47.286413%2C11.398326&locale=de&vehicle=hike&weighting=fastest&elevation=true&turn_costs=false&use_miles=false&layer=TF%20Outdoors
- https://graphhopper.com/maps/?point=47.286413%2C11.398326&point=47.29842%2C11.391975&point=47.312133%2C11.383832&locale=de&vehicle=hike&weighting=fastest&elevation=true&turn_costs=false&use_miles=false&layer=TF%20Outdoors

Downwards looks a good guess; Upwards though is much too quick. Reasonably, the hike should be close to 4hrs, which still is quite an accomplishment, that only can be got at with training, but might match the DAV rate too.

PS: Intermediate marker to take the preferred path, where the hiking route runs, which is even shorter a little

**Comment by otbutz** [comment] 2020-11-24 13:16
https://github.com/graphhopper/graphhopper/issues/1597#issuecomment-615365980 looks intended?

**Comment by karussell** [comment] 2020-11-24 13:59
For the PR this was intended, yes. But in general we should make a difference between up+downhill for hiking too.

**Comment by hungerburg** [comment] 2020-11-24 20:20
Thank you, I know, that there are people that use graphhopper for hiking, so this will be welcome news for sure. Another example close by to help in calibration, nearly the same specs:

- Guidepost - https://www.carto.net/andre.mw/photos/2008/10/05_hoetting_rauschbrunnen/20081005-145836_wegweiser_beim_gasthof_rauschbrunnen.shtml
- Hohe Warte 4:00h  vs 2:29h - https://graphhopper.com/maps/?point=47.279313%2C11.347407&point=47.301614%2C11.33346&locale=de&vehicle=hike&weighting=fastest&elevation=true&turn_costs=false&use_miles=false&layer=TF%20Outdoors
- Aspachhütte 1:15h vs. 0:53h - https://graphhopper.com/maps/?point=47.279313%2C11.347407&point=47.284033%2C11.335015&locale=de&vehicle=hike&weighting=fastest&elevation=true&turn_costs=false&use_miles=false&layer=TF%20Outdoors

The photo is old, but people did not change that much since then. Aspachhütte lies on the way to Hohe Warte, The factor graphhopper->sign is 1.6 rsp. 1.7 : When hiking, a quarter hour is the smallest division of time; with even longer hikes, half an hour becomes the smallest ;) So in this case, it is linear, for all that its worth.

**Comment by karussell** [comment] 2021-01-14 12:58
Closing in favor of #1597

**Closed by karussell** 2021-01-14 12:58 UTC
Labels: good first issue, improvement
