### ISSUE TITLE
Web UI does not properly handle different screen sizes / make it responsive

### ISSUE THREAD

**Issue by HarelM** [graphhopper/graphhopper#2005] opened 2020-04-20 07:45 UTC
**Describe the bug**
The sidebar appear at the top of the screen when using firefox to surf to http://localhost:8989/
Also there's no icon for car4wd profile... (small bug)

**To Reproduce**
1. Surf to http://localhost:8989/ using firefox on windows

**Expected behavior**
The sidebar should be at the side like in chrome

**System Information**
Used latest code: 1.0-pre33.4

**Screenshots & Logs**
![image](https://user-images.githubusercontent.com/3269297/79726635-c9a63c00-82f3-11ea-8211-6ed4e27919af.png)

**Comment by easbar** [comment] 2020-05-11 20:56
FF/Ubuntu works fine (for me at least). Why is the map not visible on your screenshot?

**Comment by HarelM** [comment] 2020-05-11 21:01
I'm using FF on windows.
Not sure why I don't see any tiles, but switching to another source shows the map, it might be an issue but not the one reported here :-)

**Comment by easbar** [comment] 2020-05-11 21:04
Ok I was asking because its a bit hard to tell from your screen shot what the problem is. You mean the side bar is on the left but does not go all the way to the bottom of the screen?

**Comment by HarelM** [comment] 2020-05-11 21:14
Sorry, it happens also in chrome. I saw it on the a server I have which has poor resolution when using remote desktop.
When I make the browser "zoom" in to 150% in chrome and 120% in firefox the map moves down and the sidebar stays at top:
Chrome:
This happens in https://graphhopper.com/maps as well:
![image](https://user-images.githubusercontent.com/3269297/81612400-70f32c00-93e5-11ea-8979-17b75e83830d.png)
Firefox:
![image](https://user-images.githubusercontent.com/3269297/81612438-7badc100-93e5-11ea-8000-bb6485b87cb7.png)

**Comment by easbar** [comment] 2020-05-11 21:19
Ah so its a zooming issue. I can reproduce this too, but if I keep zooming more the map moves to the right of the sidebar again :) Generally, the web UI does not properly deal with different screen sizes, for example I cannot use it on my phone because the sidebar is so large I cannot even see the map.

**Comment by HarelM** [comment] 2020-05-12 06:58
I would suggest to adopt a responsive framework from one of the following top 5:
https://www.themexpert.com/blog/top-5-responsive-css-framework
I've had the chance to work with bootstrap and it is very good, but it's a bit old in terms of web and I think less and less companies decide to work with it nowadays.
A mobile site can have the search bar at the top and the map at the bottom to facilitate for this. a responsive design is basically the definition of this issue :-).
Reading the Bulma docks seems like a lightweight css only framework which might be what you need for this. If not, you can probably take something more robust...
Ping me if you want a design review/code review or just some brainstorming... :-)

**Comment by karussell** [comment] 2021-10-01 08:46
We won't fix this. Due to our effort at https://github.com/graphhopper/graphhopper-maps

**Closed by karussell** 2021-10-01 08:46 UTC
Labels: web, improvement

**Comment by easbar** [comment] 2021-10-01 09:56
Note that a possible fix was already contributed here: #2285, this was not ready to merge yet, but maybe it is close to being mergeable.

**Comment by HarelM** [comment] 2021-10-01 10:05
If the ui is being rewritten I wouldn't invest in fixing a bug that's open for more than a year...
I'm not using this UI often, I use it when I want to make sure GH is up and running, I personally don't need anything fancy, but I did wanted to let you know there's an issue here :-)
If you are rewiring the UI make sure you use a responsive framework and I also advise to use scss since I guess some of the elements (mainly related to D3) will require some additional work.
Good luck! :-)

**Comment by easbar** [comment] 2021-10-01 10:17
> If you are rewiring the UI make sure you use a responsive framework and I also advise to use scss since I guess some of the elements (mainly related to D3) will require some additional work.

The new UI is already responsive (to some extent), but we neither use a responsive framework nor scss. Feel free to try it here: http://graphhopper.com/maps2

**Comment by HarelM** [comment] 2021-10-01 10:41
Looks a lot better on mobile!! Nice work! :-)
