### ISSUE TITLE
Can't call 'graphHopper.clean' successfully after calling 'close' on Android

### ISSUE THREAD

**Issue by ArtemNeFRiT** [graphhopper/graphhopper#718] opened 2016-05-12 09:21 UTC
We are discussing one important issue in this [topic](https://discuss.graphhopper.com/t/how-to-close-graphhopper/715/6)
Do you have any idea how this can be fixed?

Renaming instead of directly deleting works:
1. Download .zip with new graphHopper files;
2. Rename all current files (edges -> edges_old, nodes -> nodes_old etc);
3. Unzip downloaded folder with new files;
4. Initialize graphHopper with new files;
5. Delete all "old" files.

**Comment by karussell** [comment] 2016-05-12 19:45
As discussed: the workaround is to create a different instance and load from a different folder. The problem is probably related to the fact that the memory mapped file cannot be unloaded via the Java API and some native magic would be required.

**Comment by karussell** [comment] 2016-10-31 17:45
It could be that this is fixed with [this commit](https://github.com/graphhopper/graphhopper/commit/24e14e3cfc2625c8145cfa246bce11b6908e3dde#diff-51df64a4a568a4658650309e94a648f5R377) where we explicitely unload storage files on Android too. Would be nice if someone (@ArtemNeFRiT :)) could try this?

**Closed** 2020-09-25 07:41 UTC
Labels: android, bug
