### ISSUE TITLE
Graphhopper prints `Started application` though no response can be received from the server

### ISSUE THREAD

**Issue by zeladada** [graphhopper/graphhopper#1493] opened 2018-11-08 13:57 UTC
Steps to reproduce:
1. Run any process that uses a port, for example localhost:8989, such as an instance of Graphhopper
2. Run Graphhopper using the same port

Result:
Graphhopper will output:
`INFO  [2018-11-08 13:38:54,950] org.eclipse.jetty.server.AbstractConnector: Started application@3a543f31{HTTP/1.1,[http/1.1]}{localhost:8989}
INFO  [2018-11-08 13:38:54,951] org.eclipse.jetty.server.AbstractConnector: Started admin@47b67fcb{HTTP/1.1,[http/1.1]}{localhost:8990}
INFO  [2018-11-08 13:38:54,951] org.eclipse.jetty.server.Server: Started @1973ms`
However, any query to localhost:8989 will return no data at all. The admin dashboard at localhost:8990 will work and indicate everything is working, and no exceptions or anything will be logged or printed in the console. Result in Postman: 
![image](https://user-images.githubusercontent.com/7935434/48202776-c9022b80-e333-11e8-9d36-6db31d5075fa.png)

Desired behavior:
Graphhopper should fail to run and throw an exception instead of somehow binding to the same port as another process and printing `Started application`. There is no indication of what the problem is or what is causing the problem without much investigation.

**Comment by karussell** [comment] 2018-11-08 14:38
Yes, the admin dashboard is no indication that the service is running.

Does the [graphhopper-storage healthcheck](https://github.com/graphhopper/graphhopper/blob/master/web-bundle/src/main/java/com/graphhopper/http/GraphHopperBundle.java#L259) return "healthy state" in those cases?

**Comment by zeladada** [comment] 2018-11-08 15:15
Yes, `"healthy" : true` for both

**Comment by karussell** [comment] 2018-11-12 21:18
I cannot reproduce this behaviour via e.g.

```
curl localhost:8990/healthcheck
```

This call will not return until the import process is over and the graphhopper instance is ready. 

What steps do you do with e.g. the master branch to see that it returns `healthy:true` although the service is not ready yet?

Also "Started application" is the last bit in my case that is printed, i.e. the service is already ready to answer routing requests.

**Comment by zeladada** [comment] 2018-11-12 22:02
Originally, the other application was Graphhopper 0.9 running on the same port from inside a Docker container. Just running the most basic configuration `./graphhopper -i map.osm -c config.yml` from master in a new terminal window is enough to reproduce the issue for me in that case. 
I just tried running `./graphhopper -i map.osm -c config.yml` from master in two different windows at the same time and on the same port without Docker and got a `java.net.BindException` like you. 
Therefore, how Docker binds to ports/addresses must not be recognized for some reason. 


I don't know that a fix is necessary since I don't know how common this problem is, but people testing Graphhopper and using Docker or other applications where there could be two processes trying to use the same port should be aware it could fail to recognize addresses already in use.

**Comment by karussell** [comment] 2018-11-13 08:59
So, you mean you run something with docker and start the latest master on the same port and it did not throw a BindException? Do you have steps to reproduce this behaviour?

(btw: GH 0.9 run on a different port in docker, which should be fixed with 0.11 or at least in master)

**Comment by zeladada** [comment] 2018-11-15 17:33
Right, for now I'm using my own Dockerfile with a different port specified than the one provided. You can see the graphhopper Dockerfiles I used in the docker-compose folder here: https://github.com/cuappdev/ithaca-transit-backend

Assuming Docker is the issue, to reproduce one would have to run graphhopper in a Docker container then by itself on the same port.

**Closed** 2018-11-19 07:19 UTC

**Comment by IldarKhayrutdinov** [comment] 2021-06-18 10:26
> ```
> curl localhost:8990/healthcheck
> # or
> curl localhost:8990/ping
> ```
> 
> This call will not return until the import process is over and the graphhopper instance is ready.

@karussell I'm interested in this question, I'll be grateful for answer, is there anything can do that during the import process graphhopper returns response without delays, something like "I'm busy"?

**Comment by IldarKhayrutdinov** [comment] 2021-06-23 06:14
@karussell thanks, unfortunately, I didn't find such a possibility of `dropwizard`.

**Comment by easbar** [comment] 2021-06-23 09:27
During server startup there should be a line like this:

```
2021-06-23 10:52:31.510 onise main xyz INFO  bla o.e.jetty.server.AbstractConnector - Started admin@2f651f93{HTTP/1.1, (http/1.1)}{localhost:9900}
```

that tells you the port the admin interface is running on

**Comment by IldarKhayrutdinov** [comment] 2021-06-23 10:59
@easbar 

```
last Thursday at 17:53:19 2021-06-17 14:53:19.483 [main] INFO  o.e.jetty.server.AbstractConnector - Started application@73a19967{HTTP/1.1, (http/1.1)}{localhost:8989}
last Thursday at 17:53:19 2021-06-17 14:53:19.484 [main] INFO  o.e.jetty.server.AbstractConnector - Started admin@5e746d37{HTTP/1.1, (http/1.1)}{localhost:8990}
last Thursday at 17:53:19 2021-06-17 14:53:19.485 [main] INFO  org.eclipse.jetty.server.Server - Started @2303948ms
```

yes, but these messages are output after end of importing and while importing process the admin interface is unavailable

**Comment by easbar** [comment] 2021-06-23 11:22
Ok. So when it is unavailable you know the server is busy with the import (or not running at all :))
You can also run the import in a separate process instead of starting the server (use `import` instead of the `server` command)

**Comment by IldarKhayrutdinov** [comment] 2021-06-30 06:35
@easbar  thanks, it is inconvenient by unavailability, I would like to immediately receive a response about the server status without timeouts

**Comment by easbar** [comment] 2021-06-30 06:58
The import is just included in our application start, so before it is done the application is not really 'running' and the endpoints are not available yet. Like I said one workaround would be running the import command separately, then the application start will be faster (the graph data will just be loaded from disk). But maybe you can figure out if Dropwizard offers some kind of feature that allows some kind of health check during the application start?

**Comment by IldarKhayrutdinov** [comment] 2021-06-30 07:20
> But maybe you can figure out if Dropwizard offers some kind of feature that allows some kind of health check during the application start?

yes, of course, I'll check it, if find a solution, I definitely inform you
