### ISSUE TITLE
System.err.println in Bike2WeightEncoder

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper#569] opened 2015-11-23 13:10 UTC
https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/routing/util/Bike2WeightFlagEncoder.java#L176

In my opinion this should be removed or changed to logger?

**Comment by karussell** [comment] 2015-11-23 13:26
This is a could hint. The problem is: there could be several and this is somewhat unrelated to GraphHopper. See #435. Also we do writing to std err in other cases when this is not really a GraphHopper bug but should be fixed in OSM. Let us think about what to do best with these.

**Comment by boldtrn** [comment] 2015-11-23 13:55
@karussell Ah thought this would be a typo. Well in this case, I like the idea of splitting the ways on import as described in #435.

**Comment by karussell** [comment] 2015-11-23 14:07
Okay, if this is then fixed we should throw an error here or at least log as warn.

Still I'm unsure what to do if just OSM is erroneous and we cannot parse something e.g. in max speed. Or what if names are too long like [described here](http://www.openstreetmap.org/user/karussell/diary/26055) and this logging is happening [here](https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/search/NameIndex.java#L105)

**Comment by boldtrn** [comment] 2015-11-23 14:21
I guess fixing as much as possible on import is the best, report it as info or warn. Requiring to check if distance is infinite each time is not that nice in my opinion. What do you think?

BTW: It's crazy what problems arouse when working with OSM data. The russian names are crazy.

**Comment by karussell** [comment] 2015-11-23 14:23
> Requiring to check if distance is infinite each time is not that nice in my opinion

Yes, that is very ugly and we should definitely move the check to setDistance instead.

**Closed** 2015-12-01 12:00 UTC
