### ISSUE TITLE
Accessibility issue with Overlay menu

### ISSUE THREAD

**Issue by cbayerlein** [graphhopper/graphhopper#1830] opened 2019-12-19 11:41 UTC
**Describe the bug**
As a physically disabled user and developer I have an accessibility issue with the overlay menu (in the top right corner of the map). The menu automatically closes when I move the mouse 'wrongly'. I don't know what is exactly causing the menu to close. I use assistive technology (speech recognition) to control the mouse pointer, thus it's not so easy to move the pointer smootly. Can I somewhere change the JS to make the menu stay open until I explicitly close it (e. g. by clicking outside)?

**To Reproduce**
Hower mouse over overlay menu to open it. Move mouse. At some stage, the menu will close by itself.

**Expected behavior**
Menu should stay open until manually closed.

**System Information**

Webapp frontend on Chrome.

**Comment by karussell** [comment] 2019-12-19 12:16
Thanks for using GraphHopper :) ... unfortunately GraphHopper Maps is in general not very accessible and not even mobile ready. We plan to change this but this is a major undertaking, maybe we'll use a frontend from [nextcloud maps](https://github.com/nextcloud/maps) or [qwant maps](https://github.com/QwantResearch/qwantmaps) or leaflet routing machine instead. 

But for now: the overlay menu is not under our control as it is a component from leaflet.js. So either the problem is fixed in a more recent leaflet version or you need to create an issue there.

**Closed by karussell** 2019-12-19 12:16 UTC

**Comment by cbayerlein** [comment] 2019-12-19 12:24
Thanks! Can you tell me if I can file an issue at leaflet.js? Is it on GitHub?

**Comment by cbayerlein** [comment] 2019-12-19 12:25
Also, is there a way to replace leaflet by a different frontend myself (i. e. in my self hosted environment)?

**Comment by karussell** [comment] 2019-12-19 12:38
You can create whatever frontend you like, but simply replacing is not a simple task. See the linked frontends in my comment before.

**Comment by cbayerlein** [comment] 2019-12-19 19:47
Hi @karussell 

do you think the following info could help (from the corresponding issue on leaflet.js)?

https://github.com/Leaflet/Leaflet/issues/6946#issuecomment-567620007
