### ISSUE TITLE
Avoid walking on major highways with sidewalk=no

### ISSUE THREAD

**Issue by neiljp** [graphhopper/graphhopper#463] opened 2015-07-17 21:10 UTC
There are various pedestrian ways around this roundabout - and walking across the junction is not advisable! I have set sidewalk=no where appropriate:
  http://overpass-turbo.eu/s/atC

This is an example unexpected route:
https://graphhopper.com/maps/?point=57.1554%2C-2.102809&point=57.153113%2C-2.099794&vehicle=foot&locale=en-US&elevation=true&layer=OpenStreetMap

While walking on service/residential (maybe unclassified?) may be reasonable (even preferable) with no sidewalk/pavement, the higher levels of road really shouldn't route pedestrians in the absence of a pavement, right? Just avoiding primary[_link?] upwards with sidewalk=no would be a good first change?

In future having notes regarding sidewalks on different sides might be useful (crossing roads where explicit crossings aren't included?), which I think isn't present at the moment (?), but just trying to avoid walking on a major road (itself) would be a good first stage.

Apologies in advance if this exists and is awaiting a database update; I don't know of many areas to check for this.

**Comment by ratrun** [comment] 2015-07-18 05:49
See code at https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/routing/util/FootFlagEncoder.java#L405 .
Your suggestions are already implemented. Note that there is no need for a "sidewalk=no" attribute on major in order to gain bigger avoidence level on major roads.

**Comment by neiljp** [comment] 2015-07-18 10:59
I don't claim to fully understand the implementation - I'm not sure how those two 'if' statements combine through weightToPrioMap - but the route proposed in my link above could either be construed as very poor or dangerous. In that particular case, Mounthooly (yellow road) one-way roads onto the roundabout have sidewalk on one side and a crossing between them, which would be the logical and preferred choice.

If the current code prefers sidewalk=yes/both/left/right and avoids highway=primary+, in my view either the map is tagged wrongly in some way (that isn't clear to me) or the routing is really non-ideal (and might need adjusting).

**Comment by ratrun** [comment] 2015-07-19 07:37
The suggested route is 374 m. The only alternative I see via Jute Street is 1.12km:

https://graphhopper.com/maps/?point=57.1554%2C-2.102809&point=57.15675%2C-2.101897&point=57.153113%2C-2.099794&vehicle=foot&locale=en-US&elevation=true&layer=OpenStreetMap

In such cases you need to set a "via" point or adjust flag encoder according to your needs. I'm convinced that graphhopper needs allow walking on these kind of roads, because there lots of places in rural areas where theses are the only alternative.

**Comment by neiljp** [comment] 2015-07-19 12:47
The suggested route is 374m.

There is also route A: (451m)
https://graphhopper.com/maps/?point=57.1554%2C-2.102809&point=57.154455%2C-2.099633&point=57.153113%2C-2.099794&vehicle=foot&locale=en-US&elevation=true&layer=OpenStreetMap

There is also this route B: (463m)
https://graphhopper.com/maps/?point=57.1554%2C-2.102809&point=57.154161%2C-2.102385&point=57.153113%2C-2.099794&vehicle=foot&locale=en-US&elevation=true&layer=OpenStreetMap

Both of these are what I would consider the expected, safe, reasonable routes around this roundabout for pedestrians.

However, both of the above are sub-optimal routes; due to the sidewalks along the roundabout, there are also the following:
A2: (441m, saving 10m over A1; 67m more than suggested)
https://graphhopper.com/maps/?point=57.1554%2C-2.102809&point=57.15446%2C-2.100148&point=57.154472%2C-2.099639&point=57.153113%2C-2.099794&vehicle=foot&locale=en-US&elevation=true&layer=OpenStreetMap
B2: (456m, saving 7m over B1; 82m more than suggested)
https://graphhopper.com/maps/?point=57.1554%2C-2.102809&point=57.154161%2C-2.10238&point=57.153698%2C-2.101044&point=57.153113%2C-2.099794&vehicle=foot&locale=en-US&elevation=true&layer=OpenStreetMap

Those routes are longer, but far more reasonable.

I agree that walking on these roads should not be avoided entirely, due to rural areas and so on. However, there needs to be a balance, which also prefers safe passage around urban areas.

As I said, at present I haven't tried completely following how sidewalk and major roads work together for pedestrian routing in the code, but perhaps there is an alternative way to encode the logic which takes into account this problem. I may take a look at some point.

**Comment by ratrun** [comment] 2015-07-19 18:26
Now I see what you mean. This really looks strange.

**Comment by karussell** [comment] 2015-07-20 06:19
I see what you mean. Would you mind to find out the tags for these streets?

See also the discussion at https://github.com/graphhopper/graphhopper/pull/355

**Comment by ratrun** [comment] 2015-07-25 09:33
I investigated the following 130 long primary segment

https://graphhopper.com/maps/?point=57.154513%2C-2.100765&point=57.153727%2C-2.099403&vehicle=foot&layer=MapQuest

and compared the tags on the intended way, which  is 207 meters long:
https://graphhopper.com/maps/?point=57.154513%2C-2.100765&point=57.154402%2C-2.099471&point=57.153727%2C-2.099403&vehicle=foot&elevation=true&layer=MapQuest

The avoidHighwayTags in the foot encoder classified the primary road with REACH_DEST (2). This was not enough. 

I prepared a pull request at 

https://github.com/graphhopper/graphhopper/compare/master...ratrun:master

I think that the ways, which should be avoided, are so bad for walking that we need to assume it worst possible even though we loose the possibility to degrade the priority further in case that it is a tunnel. Another possibility would be to tune the Prio Weighting in
 https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/routing/util/PriorityWeighting.java#L52 for foot to become more aggressive on the priority classification.

For some reason the GraphStorageViaMMapTest failes with two tests when I compile the core, but this happens also without modifications. It is the reason that I didn't create a pull request yet:

Theses are the failures I get:

```java
Tests run: 38, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 4.224 sec <<< FAILURE! - in com.graphhopper.storage.GraphStorageViaMMapTest
testPropertiesWithNoInit(com.graphhopper.storage.GraphStorageViaMMapTest)  Time elapsed: 0.102 sec  <<< FAILURE!
java.lang.AssertionError: expected:<0> but was:<11107>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.graphhopper.storage.AbstractGraphStorageTester.testPropertiesWithNoInit(AbstractGraphStorageTester.java:114)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

testSimpleDelete2(com.graphhopper.storage.GraphStorageViaMMapTest)  Time elapsed: 0.099 sec  <<< FAILURE!
java.lang.AssertionError: expected:<-1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.graphhopper.storage.AbstractGraphStorageTester.testSimpleDelete2(AbstractGraphStorageTester.java:601)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

**Comment by karussell** [comment] 2015-07-26 14:34
Thanks a lot @ratrun for investigating this more deeply! 

No idea about the failure. Would you mind to try the clean master and see if this is okay? If not, which OS are you using?

**Comment by ratrun** [comment] 2015-07-27 17:06
I cloned the clean master for a test. It produces the same two test failures in GraphStorageViaMMapTest. The problem occurs on Windows 7 64 bit with jdk1.7.0_45 and jdk1.8.0_40. As this is something unrelated, I created the pull request. Travis-ci fails there on a foot specific test. I do not plan to look at this until somebody finds the solution for the failing GraphStorageViaMMapTest.

**Comment by karussell** [comment] 2015-07-27 19:12
Can reproduce it, opened #477

**Comment by karussell** [comment] 2015-08-10 10:11
As #477 is fixed and foot handling is improved in #476 can we close this here and #355 too?

**Comment by neiljp** [comment] 2015-08-12 10:27
As per my comment on #476, I would consider this issue sufficiently resolved now.
Do you have a set of routing test cases such as for this one?

**Comment by karussell** [comment] 2015-08-12 10:51
Indeed I need to add the problem you mentioned in #476 as test case. After this I'll close here.

**Comment by karussell** [comment] 2015-08-12 12:05
Added now, via https://github.com/graphhopper/graphhopper/commit/d3fdc549589ff0aeeeadcd623eb198ecd5c259eb

**Closed by karussell** 2015-08-12 12:05 UTC
