### ISSUE TITLE
Foot: incomplete instructions

### ISSUE THREAD

**Issue by drnextgis** [graphhopper/graphhopper#302] opened 2015-01-12 09:44 UTC
[Example](https://graphhopper.com/maps/?point=55.691995%2C37.535053&point=55.688671%2C37.553093&vehicle=foot&layer=Lyrk) contains only:

```
Continue 1.61km 19min
Finish!
```

**Comment by karussell** [comment] 2015-01-12 09:48
Duplicate of #94

**Closed by karussell** 2015-01-12 09:48 UTC
