### ISSUE TITLE
graphhopper/web: Downloaded gpx-File is called xxx.gpx.json

### ISSUE THREAD

**Issue by chrissssss** [graphhopper/graphhopper#428] opened 2015-05-31 09:02 UTC
Tested on https://graphhopper.com/maps/?point=hamburg&point=berlin&point=Frankfurt%20am%20Main%2C%20Deutschland&point=münchen&locale=de-de&layer=Lyrk

CURRENT:
Click Download link for GPX
Resulting file is called xxx.gpx.json

EXPECTED:
Resulting file is called xxx.gpx (without Suffix .json)

**Comment by karussell** [comment] 2015-05-31 09:46
Strange, for me the file name is always GraphHopper.gpx

What browser and OS are you using?

**Comment by chrissssss** [comment] 2015-05-31 10:55
It's latest Safari on Mac OS X Yosemite.
Am 31.05.2015 11:46 schrieb "Peter" <notifications@github.com>:

**Comment by karussell** [comment] 2015-06-01 07:53
Still can't reproduce it on an older mac/safari, but as it prints 'JSON file' in the download dialog something is wrong here.

**Comment by karussell** [comment] 2015-09-24 13:05
There was a bug I fixed now in our authentication layer for the Directions API which assumed JSON for an empty Content-Type in the request. Can you please verify if this also fixes your problem?

**Comment by karussell** [comment] 2015-10-06 16:27
Please reopen if not fixed for you.

**Closed by karussell** 2015-10-06 16:27 UTC
Labels: web

**Comment by chrissssss** [comment] 2015-10-06 18:17
Working. File is now called Graphhopper.gpx

**Comment by karussell** [comment] 2015-10-06 18:22
Perfect - thanks for confirming this!
