### ISSUE TITLE
When there are many points in block_area, routing still passes through it.

### ISSUE THREAD

**Issue by ErikBorra** [graphhopper/graphhopper#1418] opened 2018-06-29 08:02 UTC
I have about 200 lat/lon/radius specified in block_area. However, routing often does not respect the values in block_area. When there are a lot of blocked points, routing still passes through the radius of those points.

The green path shows a clear example: https://image.ibb.co/c8ihaT/Screen_Shot_2018_06_22_at_20_48_06.png 2

Here’s the relevant code snippet using the Web API:
```
var ghRoutingAvoid = new GraphHopper.Routing({
                key: "API_KEY",
                vehicle: "foot",
                elevation: false,
                instructions: false,
                ch: {disable: true},
                block_area: "LONG LIST OF LAT,LON,RADIUS"
            });

            setupRoutingAPIAvoid(map, ghRoutingAvoid);

            function setupRoutingAPIAvoid(map, ghRouting) {
                map.setView([52.093421, 5.073712], 12);
                ghRouting.addPoint(new GHInput(52.08986,5.1113));
                ghRouting.addPoint(new GHInput(52.09086,5.1193099));
                ghRouting.doRequest()
                    .then(function(json) {
                        var path = json.paths[0];
                        routingLayerAvoid.addData({
                            "type": "Feature",
                            "geometry": path.points
                        });

                    }).catch(function(err) {
                        console.log(err);
                    });

                var routingLayerAvoid = L.geoJson().addTo(map);
                routingLayerAvoid.options = {
                    style: {color: "#00cc33", "weight": 5, "opacity": 0.6}
                };
            }
```

A live example can be seen [here](http://dj.digitalmethods.net/cams/graphhopper.php?van=stationsplein%2C+utrecht&naar=jansdam%2C+utrecht). The red line is a route on foot without block_area, the green line is the same route request but with block_area. No route should ever go through the block_areas. If no route can be found, no route should be shown.

**Comment by karussell** [comment] 2018-06-29 11:52
As [discussed](https://discuss.graphhopper.com/t/how-to-make-sure-block-area-is-always-respected/3212), likely a duplicate of #1324

**Closed by karussell** 2018-06-29 11:52 UTC
