### ISSUE TITLE
Problem with bicycle=yes and vehicle=destination

### ISSUE THREAD

**Issue by ratrun** [graphhopper/graphhopper#1831] opened 2019-12-19 17:25 UTC
Following route https://graphhopper.com/maps/?point=48.179737%2C16.115484&point=48.175072%2C16.122608&locale=de&vehicle=bike&weighting=fastest&elevation=true&use_miles=false&layer=Omniscale results in a big unexpected de-tour. I found out that one needs to remove the tags `vehicle=destination` and `motor_vehicle=destination` from way https://www.openstreetmap.org/way/155156339 in order to get an expected result.
To me it looks to be a problem outside of the bicycle specific routing because I couldn't create a bicycle specific test to nail down this problem.

**Comment by karussell** [comment] 2019-12-19 19:31
Strange. Especially since https://github.com/graphhopper/graphhopper/pull/1272 is not yet merged. And your request seems to support my claim that we should not support this tag for bike and foot.

So surely we need to investigate what is wrong here.

**Comment by boldtrn** [comment] 2020-01-16 08:00
Isn't this the expected behavior? If an edge is tagged with vehicle=destination, the bike flag encoder will pick this up and set the RoadAccess to destination. RoadAccess is a required encoded value, so it's always used, right? The fastest weighting will add the edge penalty for destination access. 

As mentioned in #1272, we could think about not using the destination tag at all for bike and foot.

**Comment by karussell** [comment] 2020-01-16 12:38
> If an edge is tagged with vehicle=destination, the bike flag encoder will pick this up and set the RoadAccess to destination (vehicle is added to restrictions for bikes). 

Thanks, indeed, this is the reason. 

Having such an example still helps to see that even an explicit bicycle=destination should be ignored here.

I again parsed some forum entries and many mapper believe that a sign which shows 

"bicycles only OR destination only" means `highway=cycleway` and `vehicle=destination`

which is IMO a tagging mistake and instead `highway=cycleway` and `motor_vehicle=destination` should be used. Discussed e.g. [here](https://forum.openstreetmap.org/viewtopic.php?id=57874 (German).

In general there are several mistakes where vehicle=x is used instead of motor_vehicle=x, but there does not seem to be even a sign that really means ["vehicle=destination (i.e. with foot and bike)"](http://osmtools.de/traffic_signs/?signs=250,1020-30).

And as this makes bike+foot routes worse like here, we should consider closing #1272.

Maybe even removing the destination restriction for the bike + foot routing in general that would fix this issue here. Thoughts @ratrun ?

**Comment by ratrun** [comment] 2020-01-16 18:47
> If an edge is tagged with vehicle=destination, the bike flag encoder will pick this up and set the RoadAccess to destination (vehicle is added to restrictions for bikes).

I guess here you mean this line of code in `BikeCommonFlagEncoder`:
`restrictions.addAll(Arrays.asList("bicycle", "vehicle", "access"));`

I tried to remove the "vehicle" from this list, recompiled and tested the example above, but this does not help. This explaination also does not explain that I need to remove both tags `vehicle=destination` and `motor_vehicle=destination` in order to fix the issue.

**Comment by boldtrn** [comment] 2020-01-17 08:00
Yes indeed, there are quite a lot of tagging mistakes in that area.

> but there does not seem to be even a sign that really means "vehicle=destination (i.e. with foot and bike)".

AFAIK in Germany, the sign is the red circle, with white background and an attached sign "Anlieger frei", see for example this file: https://commons.wikimedia.org/wiki/File:Wuppertal_Carnaper_Stra%C3%9Fe_2018_039.jpg

This should be vehicle=destination, including bikes. I think pedestrians are still allowed to pass. I am not sure if there are other signs.

> I tried to remove the "vehicle" from this list, recompiled and tested the example above

Did you also reimported the graph?

**Comment by ratrun** [comment] 2020-01-17 16:15
> Did you also reimported the graph?

Yes I did. I do not see any tagging error as the tagging is according to this signs: http://osmtools.de/traffic_signs/?signs=250,1020-12 which means "Fahrrad und Anlieger frei", therefore the way also has a tag `bicycle=yes`.

**Comment by boldtrn** [comment] 2020-01-18 10:26
That's strange, maybe we should debug what happens here.

**Comment by ratrun** [comment] 2020-01-18 14:29
I would ask for debugging. How ever this can be done in this case. I don't know it.
What I tried is playing around with this test:
```        way.clearTags();
        way.setTag("highway", "service");
        way.setTag("surface", "asphalt");
        way.setTag("bicycle", "yes");
        way.setTag("vehicle", "destination");
        //way.setTag("motor_vehicle", "destination");
        assertEquals(18, encoder.getSpeed(way));
        assertPriority(PREFER.getValue(), way);
        assertTrue(encoder.getAccess(way).isWay());
```

This test passes irrespsective if `vehicle=destination` and `motot_vehicle=destination` is included or not.

**Comment by karussell** [comment] 2020-02-06 12:19
Yeah, this seems to be a bug. [Here is another example](https://graphhopper.com/maps/?point=51.529358%2C4.398394&point=51.520226%2C4.418736&vehicle=bike) that uses `motor_vehicle:destination` and should not affect `bike`.

**Comment by ratrun** [comment] 2020-02-25 18:32
Maybe I now found the reason:

https://github.com/graphhopper/graphhopper/blob/0ea8d4613cef3b378acb1acbb9330dcc8d4afc5a/core/src/main/java/com/graphhopper/routing/weighting/FastestWeighting.java#L91-L92

If I comment out these two lines then the segment tagged as `motor_vehicle=destination` is taken. This code part is not aware of the `bicycle=yes` tag

**Comment by karussell** [comment] 2020-02-25 20:07
Ah, thanks, indeed this is wrong!!

**Closed** 2020-02-27 16:05 UTC
Labels: bug

**Comment by karussell** [comment] 2020-02-27 16:06
Thanks again @ratrun for the investigation! Will hopefully be deployed next week.

**Comment by karussell** [comment] 2020-03-16 12:59
Took a bit longer but is now deployed :)
