### ISSUE TITLE
Runtime Map Matching through gps direction

### ISSUE THREAD

**Issue by DrPoldo** [graphhopper/graphhopper#391] opened 2015-04-03 14:10 UTC
I'm using graphhopper to calculate the distance covered by some vehicles through their gps tracker and I love it, it's really a great project.
Testing the results i have found some differences between the real distance and the one calculated.
I've found that most of the time these differences are caused by situations like [this](https://graphhopper.com/maps/?point=52.575809%2C13.323519&point=52.571323%2C13.330874&point=52.569999%2C13.332419&locale=en-US&layer=Lyrk).

As you can see the middle point is matched on the closest edge but the right one is a bit more on the left. This situation happen a lot of times because is related with highways and similar routes.

I know i could use the [map-matching class](https://github.com/graphhopper/map-matching) but in my case this would require too much computation.
Currently i calculate the distance passing only two points at the time(the last and previous vehicle position ) to graphhopper.

To solve this problem I would like to implement a LocationIndex that take into consideration the direction of the gps points and match the edges with similar direction.

As i'm new to this project and i'd appreciate any help that point me in the right direction (It's always a matter of direction ;D ).

**Comment by dos65** [comment] 2015-04-03 14:18
Try ti use special edgeFilter for LocationIndex.findClosest method, example: https://gist.github.com/dos65/574cc169a8630e0116e5

**Comment by DrPoldo** [comment] 2015-04-03 15:40
Thanks a lot, that's what I was looking for.
I've just made some minor changes:
```java
	public boolean accept(EdgeIteratorState edge) {
		long flags = edge.getFlags();
		if(encoder.isBackward(flags) && encoder.isForward(flags))
			return true;
```
Hope this is correct, I haven't found "Helper.isBidirect(...)" i think that's due to the version (I'm running 5.0 snapshot). 

To pass point direction to GraphHopperServlet i was thinking to subclass or modify GHPoint or do you know if there's a better way?

**Comment by devemux86** [comment] 2015-04-03 16:08
May be related to #225.

**Comment by dos65** [comment] 2015-04-03 16:24
@DrPoldo , it is just out of date code from my old branch. About GHPoint, yes i think it is right way.

I don't think that is issue, it can be closed.

**Comment by DrPoldo** [comment] 2015-04-03 16:30
I'm just missing one thing, maybe it's  something obvious but what i have to pass as NodeAccess to the EdgeFilterDirection constructor?

**Comment by DrPoldo** [comment] 2015-04-03 16:31
Thanks devemux86, I'll do in that way to initialize the edgefilter.

**Comment by dos65** [comment] 2015-04-03 17:08
@DrPoldo Although now I think that my example is bad way to find closest by direction, because ways can have geometry not only like line. I didn't look at map-matching yet, but maybe there is more lightly way for this case.

**Comment by karussell** [comment] 2015-04-07 08:48
Yes, this is a duplicate of #225 or just provide the list of points for the map-matching component which would do the rest. Why do you think it would require too much computation? Because the map-matching component is not using CH?

**Comment by karussell** [comment] 2015-05-27 10:02
I'm closing here for now, please reopen if you think it is not a duplicate.

**Closed by karussell** 2015-05-27 10:02 UTC
