### ISSUE TITLE
Error import with setMemoryMapped since 0.4

### ISSUE THREAD

**Issue by schoeso** [graphhopper/graphhopper#372] opened 2015-03-16 12:04 UTC
During the initial import of the pbf File (I use germany) I get an error when I am using the option „setMemoryMapped“ since version 0.4. The same code worked for 0.3.

My testmethod for the import
```java
public GHResponse calc() {
        this.getHopper().setOSMFile(e:/germany-latest.osm.pbf);
        this.getHopper().setGraphHopperLocation(e:/ghStorage);
        EncodingManager encodingManager = new EncodingManager(EncodingManager.CAR);
        this.getHopper().setEncodingManager(encodingManager);
        this.getHopper().setCHWeighting("fastest");
        this.getHopper().setMemoryMapped();
        this.getHopper().importOrLoad();
        GHRequest gHRequest = new GHRequest(fromLat, fromLon, toLat, toLon).setWeighting("fastest").setVehicle("car");
        GHResponse ghResponse = this.getHopper().route(gHRequest);
        return ghResponse;
    }
```
It seems to be a file access problem (acces to a locked file). The error appears only during the import. If I import inMemory and switch after this to setMemoryMapped everything works.

The log
```log
2015-03-16 12:42:59,754 [main] INFO  com.graphhopper.GraphHopper - version 0.4|${builddate} (4,12,3,2,2)
2015-03-16 12:42:59,769 [main] INFO  com.graphhopper.GraphHopper - graph LevelGraphStorage|car|MMAP_STORE|2D|NoExt|,,,,, details:edges:0(0), nodes:0(0), name: /(0), geo:0(0), bounds:1.7976931348623157E308,-1.7976931348623157E308,1.7976931348623157E308,-1.7976931348623157E308
2015-03-16 12:42:59,785 [main] INFO  com.graphhopper.GraphHopper - start creating graph from e:/projects/001_schoeso/15_GraphHopper/germany-latest.osm.pbf
2015-03-16 12:42:59,785 [main] INFO  com.graphhopper.GraphHopper - using LevelGraphStorage|car|MMAP_STORE|2D|NoExt|,,,,, memory:totalMB:244, usedMB:7
2015-03-16 12:45:04,242 [main] INFO  graphhopper.reader.OSMReader - 5 000 000 (preprocess), osmIdMap:31 506 627 (403MB) totalMB:2018, usedMB:1230
2015-03-16 12:45:14,555 [main] INFO  graphhopper.reader.OSMReader - 50 000 (preprocess), osmWayMap:0 totalMB:2105, usedMB:1503
2015-03-16 12:45:14,728 [main] INFO  graphhopper.reader.OSMReader - 100 000 (preprocess), osmWayMap:0 totalMB:2105, usedMB:1751
2015-03-16 12:45:14,931 [main] INFO  graphhopper.reader.OSMReader - 150 000 (preprocess), osmWayMap:0 totalMB:2097, usedMB:1185
2015-03-16 12:45:15,071 [main] INFO  graphhopper.reader.OSMReader - 200 000 (preprocess), osmWayMap:0 totalMB:2097, usedMB:1400
2015-03-16 12:45:15,196 [main] INFO  graphhopper.reader.OSMReader - 250 000 (preprocess), osmWayMap:0 totalMB:2097, usedMB:1584
2015-03-16 12:45:15,305 [main] INFO  graphhopper.reader.OSMReader - 300 000 (preprocess), osmWayMap:0 totalMB:2097, usedMB:1768
2015-03-16 12:45:15,492 [main] INFO  graphhopper.reader.OSMReader - 350 000 (preprocess), osmWayMap:0 totalMB:2039, usedMB:1180
2015-03-16 12:45:15,602 [main] INFO  graphhopper.reader.OSMReader - 400 000 (preprocess), osmWayMap:0 totalMB:2039, usedMB:1358
2015-03-16 12:45:15,712 [main] INFO  graphhopper.reader.OSMReader - creating graph. Found nodes (pillar+tower):34 099 680, totalMB:2039, usedMB:1521
2015-03-16 12:46:16,864 [main] INFO  graphhopper.reader.OSMReader - 100 000 000, locs:24 806 533 (0) totalMB:2351, usedMB:625
2015-03-16 12:47:08,470 [main] INFO  graphhopper.reader.OSMReader - 200 000 000, locs:33 790 723 (0) totalMB:2373, usedMB:1227
2015-03-16 12:47:11,138 [main] INFO  graphhopper.reader.OSMReader - 205 205 080, now parsing ways
2015-03-16 12:49:15,243 [main] INFO  graphhopper.reader.OSMReader - 237 623 522, now parsing relations
2015-03-16 12:49:16,523 [main] INFO  graphhopper.reader.OSMReader - finished way processing. nodes: 8175826, osmIdMap.size:34217411, osmIdMap:410MB, nodeFlagsMap.size:117731, relFlagsMap.size:0 totalMB:2364, usedMB:897
2015-03-16 12:49:17,475 [main] INFO  graphhopper.reader.OSMReader - time(pass1): 135 pass2: 241 total:377
2015-03-16 12:49:17,491 [main] INFO  com.graphhopper.GraphHopper - start finding subnetworks, totalMB:2318, usedMB:493
2015-03-16 12:49:22,437 [main] INFO  routing.util.PrepareRoutingSubnetworks - optimize to remove subnetworks (145232), zero-degree-nodes (0), unvisited-dead-end-nodes(-1), maxEdges/node (13)
java.lang.Error: Cleaner terminated abnormally
	at sun.misc.Cleaner$1.run(Cleaner.java:130)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.misc.Cleaner.clean(Cleaner.java:127)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.graphhopper.util.Helper$1.run(Helper.java:435)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.graphhopper.util.Helper.cleanMappedByteBuffer(Helper.java:424)
	at com.graphhopper.storage.MMapDataAccess.clean(MMapDataAccess.java:405)
	at com.graphhopper.storage.MMapDataAccess.trimTo(MMapDataAccess.java:424)
	at com.graphhopper.storage.GraphHopperStorage.trimToSize(GraphHopperStorage.java:1158)
	at com.graphhopper.storage.GraphHopperStorage.optimize(GraphHopperStorage.java:1152)
	at com.graphhopper.routing.util.PrepareRoutingSubnetworks.doWork(PrepareRoutingSubnetworks.java:90)
	at com.graphhopper.GraphHopper.cleanUp(GraphHopper.java:1102)
	at com.graphhopper.GraphHopper.process(GraphHopper.java:678)
	at com.graphhopper.GraphHopper.importOrLoad(GraphHopper.java:645)
	at de.schoeso.test.ImportTest.calc(ImportTest.java:71)
	at de.schoeso.test.ImportTest.main(ImportTest.java:84)
Caused by: java.io.IOException: Der Prozess kann nicht auf die Datei zugreifen, da ein anderer Prozess einen Teil der Datei gesperrt hat
	at sun.nio.ch.FileChannelImpl.unmap0(Native Method)
	at sun.nio.ch.FileChannelImpl.access$100(FileChannelImpl.java:32)
	at sun.nio.ch.FileChannelImpl$Unmapper.run(FileChannelImpl.java:667)
	at sun.misc.Cleaner.clean(Cleaner.java:125)
	... 16 more
```

**Comment by karussell** [comment] 2015-03-17 10:21
Hmmh, not sure why now there is a problem. I guess you are under Windows? As a workaround you should be able to comment out `graph.optimize();` in the GraphHopper class

**Comment by karussell** [comment] 2015-03-18 17:22
I can't reproduce this on my windows machine. Would you please tell us the specific version of your OS and java (`java -version` output)? Also can you try the identical OSM file on 0.3? And where is your PBF file located, on an external disc, a read only file system, ssd or a normal hard drive?

**Comment by schoeso** [comment] 2015-03-19 07:43
The error occure only with JDK 6 (Java Version: 1.6.0_45). In JDK 7 everything is ok (I tested it yesterday).
Windows 7 Professional (with all sp and patches)
The File is located on the local disc (ssd - r/w).

**Comment by karussell** [comment] 2015-03-19 18:08
Aha, okay. Yes, in JDK7 fixed several IO stuff so if you can live with this I would close this, otherwise we could introduce an optional skipping of the optimize call.

**Comment by schoeso** [comment] 2015-03-20 04:38
For me its fine. Legacy JDK6 projects could be switched to setMemoryMapped after import or have to use files from an other import - that works too.
Thank you!

**Closed** 2015-04-28 21:44 UTC
