### ISSUE TITLE
highway=track is never taken into account although routing across them might be "shorter"

### ISSUE THREAD

**Issue by jase88** [graphhopper/graphhopper#253] opened 2014-09-03 08:37 UTC
I haven't read the source code, but as far as i know GraphHopper never uses highway=track for routing. I think there might be cases where routing via tracks (especially when these parts are short) should be considered.

Here is a simple example:
https://graphhopper.com/maps/?point=54.327536%2C9.908702&point=54.325459%2C9.911342
7km vs. >1km and  5min vs. >1min.

There might be better examples with much more indirect way when not navigating through a track.

In my opinion there should be a mechanism to detect if there is an shorter option via track (let's say if it saves about 400%of time or something). Maybe an algorithmic function can be found to take this into account.

I know integrating something like this might be very time intensive for developers, but should be made possible for the future.

**Comment by karussell** [comment] 2015-01-06 12:43
As this came up [on the mailing list](https://lists.openstreetmap.org/pipermail/graphhopper/2015-January/001528.html) again I had a look into your first example. One part of the way is tracktype=grade3 which is currently not allowed - [only grade1](https://github.com/graphhopper/graphhopper/blob/65fd6ff5771b5a0df47b574d4f91cefc89a0c87a/core/src/main/java/com/graphhopper/routing/util/CarFlagEncoder.java#L184)

The problem is now really that some countries require 'track usage' and others like Austria forbid this, so related to #175 but will think about it.

**Comment by asianrider** [comment] 2015-01-06 12:47
Here's another example where it's critical that tracks are taken in account:

https://graphhopper.com/maps/?point=Dakhla%20الداخلة%2C%20Morocco&point=Nouadhibou%2C%20Mauritania&layer=MapQuest

Actually, tracks are taken in account, but only when tracktype = grade1. It should be extended to grade2 (above example) and even grade3 (OP example). Here's the relevant bit from CarFlagEncoder.acceptWay:

    if (tt != null && !tt.equals("grade1"))
        return 0;

**Comment by kerosin** [comment] 2015-01-06 13:17
I would take every highway into account unless access-restrictions or maxheight or something forbid passing there. Imho this would be the only way for worldwide optimised routes.

Naive thoughts:
Every highway should have a base factor, that is hierarchical (primary>secondary etc) and certain tags are voting this factor up or down (tracktype, surface,smoothness etc). So you got diferent routes with factors for every piece of road. Now we could make use of the length of the ways and weight them with this factor.

By the way I don't know anything about the algorithms at Graphhopper, I just want to share my view :eyeglasses: You already mentioned that tags already considered for bikes and foot routes.

It does make sense to use a (short) way with a bad conditions if you are saving a lot of kilometers/miles! Especially in countries where there is a bad road network (for whatever the reason might be) that is essential to access some places like in 3rd world countries or huge countries like Australia.

**Comment by karussell** [comment] 2015-01-15 12:18
> Imho this would be the only way for worldwide optimised routes.

The problem is country specific defaults. So we really need #175 before including more streets which make problems in other countries. E.g. a track is often mapped without access restrictions and the default in Germany is that you can access it but in Austria the default is that it is forbidden.

**Comment by asianrider** [comment] 2015-01-15 17:01
Hmmmm… where do you get the information from ? is it austrian law ? there’s a proposal on openstreetmap that says otherwise:

http://wiki.openstreetmap.org/wiki/OSM_tags_for_routing/Access-Restrictions#Austria

so I would expect the mappers to follow this. But of course not all mappers follow the recommendations, we have to cope with thousands of different mappers with different ideas. If really all tracks are forbidden by default in some country, then a postgres sql request should take care of it all at once in the master DB. Or we could do it when we process the pbf - as proposed below.

At the end of the day, though, the ways that are not marked as access=no (or motorvehicle=no, etc..), in the DB or by post-processing, should be taken in account in the algorithm.

Now I don’t think this is such a big deal, if the speed is mapped to a pretty low value for those tracks, then a longer route through paved roads should be selected by the routing algorithm 99.9% of the time. Maybe we could do a test with, e.g., a new vehicle type such as 4x4 or motorbike, then we could compare and see if it really makes such a big difference ?

Laurent

**Comment by karussell** [comment] 2015-01-15 20:44
Thanks Laurent, not read the law, I had spoken with one from Austria :)

> Now I don’t think this is such a big deal, if the speed is mapped to a pretty low value for those tracks, 
> then a longer route through paved roads should be selected by the routing algorithm 99.9% of the time. 

That is a very good argument :) ! We can think about including at least grade2 before we properly implement this via #175

**Comment by karussell** [comment] 2015-01-16 16:16
The workaround won't close this issue, but maybe suited for everyone ;). Will be live in ~2 days.

**Closed as completed** 2023-03-27 15:56 UTC
