### ISSUE TITLE
Display alternate route options

### ISSUE THREAD

**Issue by sharmibas** [graphhopper/graphhopper#2347] opened 2021-06-19 22:23 UTC
Display top optimal route options (could limit to 2-3) so that user could pick depending on their preference.

Something like : https://www.google.com/maps/dir/Summer+Rose+Dr,+Chamblee,+GA+30341/Georgia+Institute+of+Technology,+North+Ave+NW,+Atlanta,+GA/@33.8483879,-84.399029,12z/data=!4m14!4m13!1m5!1m1!1s0x88f509be02af7427:0xbb58326f7b5ff528!2m2!1d-84.295789!2d33.909666!1m5!1m1!1s0x88f5048aebc34fe3:0xb52ad03e3ad8c50f!2m2!1d-84.396285!2d33.7756178!3e0

**Comment by sharmibas** [comment] 2021-06-19 22:24
I am working on this and will be submitting a PR

**Comment by easbar** [comment] 2021-06-20 06:00
Note that a rewrite of the web app is in progress that already does this: http://www.graphhopper.com/maps2

**Comment by easbar** [comment] 2021-06-21 07:32
Btw this is related, if not a duplicate of https://github.com/graphhopper/graphhopper/issues/660

**Comment by karussell** [comment] 2021-06-21 08:03
Yes, I think this is a dup.

**Closed by karussell** 2021-06-21 08:03 UTC
Labels: web
