### ISSUE TITLE
Android demo on master has problems to access local storage

### ISSUE THREAD

**Issue by basitobaid** [graphhopper/graphhopper#704] opened 2016-04-18 15:01 UTC
I was using Graphhopper android project in my project. it was working super fine before the recent updation in the graphhopper.java file of GitGub repository. i posted this issue on stackoverflow but didn't get answer. here is the link. [http://stackoverflow.com/questions/36679112/an-error-happened-while-creating-graph-path-storage-emulated-0-graphhopper-maps].

> directory is present in phone memory.. the app downloads maps and when it comes to open maps it start giving the error shown in figure.
> i am using the demo android project of GitHub repository.
> and by apk version, if you are asking about graphhopper then it is 0.7

**Comment by karussell** [comment] 2016-04-18 15:04
Please at least take the time to read the text that was there before you posted this issue. Why should I take time to read your post now :) ?

Closing and please move this to our forum. No bad purpose or something just not the correct process as the wrong people get this notification then.

**Comment by karussell** [comment] 2016-04-19 07:35
After having the [discussion](https://discuss.graphhopper.com/t/graphopper-android-project-of-github-giving-error-about-file-path-when-loading-map-file/673) this turned out to be indeed a bug in the demo of the latest master.

Thanks @basitobaid for the report!

**Comment by devemux86** [comment] 2016-04-19 07:51
Yes I can confirm it too (tested on Android 5 device).

It appears the latest #644 changes play a role in this.
Debugging the process the following exception appears:

```java
java.lang.IllegalStateException: Path "/storage/sdcard0/Download/graphhopper/maps/europe_germany_berlin" does not exist
    at com.graphhopper.GraphHopper.load(GraphHopper.java:798)
    at com.graphhopper.android.MainActivity$7.saveDoInBackground(MainActivity.java:438)
    at com.graphhopper.android.MainActivity$7.saveDoInBackground(MainActivity.java:434)
    at com.graphhopper.android.GHAsyncTask.doInBackground(GHAsyncTask.java:15)
```

**Comment by karussell** [comment] 2016-04-19 08:15
Ah, the problem is more the missing '-gh' at the end of the folder!?

**Comment by devemux86** [comment] 2016-04-19 08:50
Yes, before the `GraphHopper` load changes, in case of missing '-gh', it was [added](https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/GraphHopper.java#L819-L820) automatically.

**Comment by karussell** [comment] 2016-04-19 09:17
Could be a missing core feature, hmmh.

**Comment by karussell** [comment] 2016-04-19 09:58
But if we cannot solve this differently I would be okay to break existing code and let developers know this change in the changelog.txt

As this implicit fallback could make trouble elsewhere, maybe the other unzipping etc should be also removed for consistency or moved 'upwards' in the code somehow.

**Comment by devemux86** [comment] 2016-04-19 10:15
Probably the code should not make automatic transformations for things like paths?
So current situation doesn't seem "wrong", i.e. passing a non actual path should cause an error.

About unzip, it's a special case and would be convenient to keep it somehow.

**Comment by karussell** [comment] 2016-04-19 10:25
> So current situation doesn't seem "wrong", i.e. passing a non actual path should cause an error.

Okay, agreed! So we keep the change and further change the Android demo, then this in the changelog.

**Comment by karussell** [comment] 2016-04-19 11:07
@basitobaid please try with the latest fix (snapshots will be deployed daily only)

**Comment by basitobaid** [comment] 2016-04-19 11:42
sir @karussell i should redownload the demo app or just run the previous code?

**Comment by karussell** [comment] 2016-04-19 11:46
You would need to wait for a new snapshot (in ~7h) and then you can try the demo app or build it from source.

**Comment by basitobaid** [comment] 2016-04-19 11:53
ok

**Comment by devemux86** [comment] 2016-04-19 12:06
I just checked the source and it seems to works again.

**Comment by karussell** [comment] 2016-04-24 15:01
This works for me too.

**Closed by karussell** 2016-04-24 15:01 UTC
Labels: android, bug
