### ISSUE TITLE
Sum of vertical moves

### ISSUE THREAD

**Issue by faon** [graphhopper/graphhopper#856] opened 2016-11-04 16:52 UTC
I prepare my bike trips using your GraphHopper, and was astonished to see the cumulative slope results.
It seems so largely overestimated that I wonder if a better filter for low-level altitude noise could be the solution.

Consider a synthetic example to explain my view :

Take a one km trip, along a canal (to be sure to consider a flat traject ;-) : if the elementary nodes are taken for each meter, and the altitude jitters within one meter of precision.
The additions will give : total climb 500m, and total descent 500m !

**Comment by fbonzon** [comment] 2016-11-04 19:45
Duplicate of #517 ?

**Comment by faon** [comment] 2016-11-04 20:02
--- 
Dr Alain EMPAIN, Bioinformatics, Bryology 
National Botanic Garden of Belgium 
University of Liège, GIGA +1, Alma-in-silico alain.empain@ulg.ac.be 
Rue des Martyrs, 11 B-4550 Nandrin 
Mobile: +32 497 701764 HOME:+32 85 512341 

----- Original Message -----

| From: "François B" <notifications@github.com>
| To: "graphhopper/graphhopper" <graphhopper@noreply.github.com>
| Cc: "Alain EMPAIN" <alain.empain@ulg.ac.be>, "Author"
| <author@noreply.github.com>
| Sent: Friday, 4 November, 2016 8:45:58 PM
| Subject: Re: [graphhopper/graphhopper] Sum of vertical moves (#856)

| Duplicate of #517 ?
Indeed, 

sorry for the duplication, it is exactly what I described. 

Hoping to receive correct estimations for cumulative climbing next year ! 

Best regards, congratulation 

Alain 

| —
| You are receiving this because you authored the thread.
| Reply to this email directly, view it on GitHub , or mute the thread .

**Comment by karussell** [comment] 2016-11-04 20:25
> Hoping to receive correct estimations for cumulative climbing next year !

Maybe you have time to contribute :) ?

**Closed by karussell** 2016-11-04 20:25 UTC
