### ISSUE TITLE
Generated GPX file contains both <rte> and <trk> tags

### ISSUE THREAD

**Issue by florent-morel** [graphhopper/graphhopper#310] opened 2015-01-27 12:56 UTC
Hi, 

as discussed separately with Peter, I am encountering issues with the GPX graphhopper generates.
Indeed, as they contain both the rte and trk tags, the softwares I use are computing both thus generating a longer route than created.

As an example, I created the following mountain bike route: 
https://graphhopper.com/maps/?point=43.87287%2C7.006069&point=43.866868%2C7.005318&point=43.851581%2C6.99415&point=43.844123%2C7.026186&point=43.839665%2C7.087083&point=43.843999%2C6.993184&point=43.849879%2C6.967607&point=43.872792%2C7.006075&vehicle=foot&elevation=true&layer=TF%20Cycle

Here is a recap of the behavior I am getting with different tools:
 - josm display both the route and the track when opening the GPX file.
 - Oruxmaps on Android considers both rte and trk, thus a 35km track becomes a 60km route+track overall. The elevation profile is pretty clear: you see more than 20kms at elevation 0 and then the real track starts.
 - this website also has the same symptoms : http://www.visugpx.com/index.php?i=N4SHU8rKaV (the URL is valid for 24hours). Here is a screenshot (which is more or less what Oruxmaps does as well):

http://www.imagehangar.com/view.php?pic=small/29703700_1422363331.jpg

I'm not sure what should exactly be the content of the gpx and I understand both route and track have their use but it would be nice to have the choice when downloading the gpx.
For example, http://www.openrunner.com/ has 2 different buttons to generate the gpx: one for route and one for track.

Any thoughts about this?

Regards,
Florent.

**Comment by karussell** [comment] 2015-01-27 14:04
IMO this is a tooling problem but yes we could offer such a functionality to separate the download, although I don't like the idea of a complex interface. And GPX export is an expert-option by itself and also not really used that often.

> josm display both the route and the track when opening the GPX file.

As separate routes?

When I e.g. use http://www.gpsvisualizer.com/ then it correctly displays them separately.

**Comment by florent-morel** [comment] 2015-01-28 15:42
gpsvisualizer indeed displays both separately on the map, but when it comes to display the elevation profile, it appends the route to the track (as opposed as visugpx and Oruxmaps) and we again end up with a 60km+ total: 

http://www.gpsvisualizer.com/display/20150128073940-48028-profile.png

**Comment by devemux86** [comment] 2015-03-20 13:15
Having added GPX support in Cruiser / Atlas lately, I started playing with the GraphHopper exported GPX file.

I'd vote too for some differentation between the turn instructions and the track in the gpx file.
They could be included as gpx waypoints instead of gpx route, so we don't confuse them with the detailed gpx track ?

**Comment by karussell** [comment] 2015-03-20 13:41
As current systems properly import the data I would just provide 3 options: both, only route, only track ... would that serve your needs?

**Comment by devemux86** [comment] 2015-03-20 13:45
Yes the gpx data are valid.
I'm talking more of them being in the same gpx file and having a route with connected the turn instructions points with straight lines, which appears a bit strange with the detailed track.
But your suggestion is fine.

**Comment by florent-morel** [comment] 2015-03-25 16:41
Indeed, having the 3 options you mentioned (both, only route, only track) would match most usages I guess.

**Comment by karussell** [comment] 2015-04-02 12:44
Another interesting option would be to split the tracks into track segments:

```xml
<trk>
        <trkseg>
            <trkpt lat="x" lon="y"></trkpt>  //Depature
            ......
            <trkpt lat="" lon=""></trkpt>
        </trkseg>
        <trkseg>
            <trkpt lat="" lon=""></trkpt> // Via-point 1
            .........
            <trkpt lat="" lon=""></trkpt>
        </trkseg>
            .........
```

**Comment by devemux86** [comment] 2015-04-02 12:51
I think GPX export has 2 aspects:
- Make optional the gpx info to be included (only one type, more than one etc.)
- What tags are to used for that info

e.g.
I'd propose the route points (start, via, end) to be "waypoints"
and the calculated route to be "track" (single or split)

**Comment by ratrun** [comment] 2015-10-04 16:34
I have implemented a popup window where the user may select via three checkboxes (route, track,waypoints) what data should be put into the GPX file. Additinally I adopted the GPX generation such that only the checked parts get written. Now I have a small problem with the export of the waypoints. I'm exporting only the start point, via points and the endpoint as suggested. The problem is that the translation string for "finish" is not a valid name for a finish point. A waypoint called "Ziel erreicht" on a GPS device sounds strange. Additionally I'm missing a translation string for the start point.
For this reason I would like to do the following:
1) Add a translation string `start_point` into https://t.co/f086oJXAEI
2) Add a translation string `finish_point` into https://t.co/f086oJXAEI. I plan to copy the content of the current finish translation to it, but leave out the "!" character. For German the translation changes from "Ziel erreicht" just into "Ziel".
3) Rename the translation string `finish` to 'finish_reached', change the string name in https://t.co/f086oJXAEI and in the code

With some minor changes to `./core/files/update-translations.sh` I was able to perform the generation of the translations text files. Therefore I would run it and afterwards prepare a pull request. 

Is this OK?

**Comment by karussell** [comment] 2015-10-04 18:25
Can you elaborate what route, track and waypoint option would include? I only see the following:

> rte represents route - an ordered list of waypoints representing a series of turn points leading to a destination. 

> trk represents a track - an ordered list of points describing a path. 

If 'waypoint' is something new I would create a separate issue for this, including the proposed translation keys. Here I would just make 3 options via Java API and web UI available: rte OR trk OR rte and trk

**Comment by ratrun** [comment] 2015-10-04 20:32
A GPX waypoint is something other on the level of "route" or "track". See
https://de.m.wikipedia.org/wiki/GPS_Exchange_Format
I would like to keep the support for it, because it is implemented now and I only have a separated commit for the java server java, but not for the java script part.  The change on the java side is very small. I'll leave the translation to a separate pull request. If really needed, I could separate it. But as this  justs costs time and I don't see any benefit, I would ask you to first take a look on it.
I'm using a Garmin GPS. Waypoints are places, which are displayed on the map with an icon. Until now, I always had to remove the route part by hand. The turn instructions messed up the way points on the device, as it also generates a separate place point for every turn. As a consequnce you see nearly nothing except icons. And  manual deletion of them on the device is a real pain. Therefore, I think that by putting only the start, the via and the endpoint to the waypoints allows the biggest flexibility for the end users, which we should reasonably support. If further flxibility is needed, the user always can use separate tools as e.g. gpsbabel.

**Comment by karussell** [comment] 2015-10-04 20:45
Ok, this makes sense.  Is wpt used normally for start/via/end points?

Please go ahead with the PR including the 4th option 'wpt-only' besides 'all', 'trk-only', 'rte-only'. Also make sure (e.g. with existing or new test) that 'all' does not break a currently consuming client, i.e. only wpt is added, the other entries stay.

**Comment by devemux86** [comment] 2015-10-05 06:13
I'm in favor too for better handling the export gpx functionality.
A more simple gpx structure would be more user convenient.

**Comment by karussell** [comment] 2015-10-05 08:15
> I'm in favor too for better handling the gpx functionality.
> A simpler gpx structure would be more user convenient.

What do you mean? This change here is only about optionally separating trk and rte, no changes to the structure are done.

**Comment by devemux86** [comment] 2015-10-05 08:19
Current situation has the routing as trk and the turn points as rte, which is a bit strange in rendering and processing in external devices (issue start comments).
That's where I'm referring too, that a better or optional selection would be beneficial.

**Comment by karussell** [comment] 2015-10-12 12:20
Merged now to master

**Closed** 2015-10-12 12:19 UTC
Labels: good first issue
