### ISSUE TITLE
Support pass_through parameter with ch

### ISSUE THREAD

**Issue by NoamDev** [graphhopper/graphhopper#2031] opened 2020-05-11 17:16 UTC
1.0 introduces curbside parameter.
I believe the same implementation which supports this in fast mode should be able to support pass_through.

# why
The basic way to implement via points is to route from A to B and then from B to C.
Now, curbside combined with force_curbside, will allow us to make sure the second route would be at the same direction the first ended.
Qed:)

I know this is merely hand-waving.
But what do you think, is it possible?

**Comment by easbar** [comment] 2020-05-11 17:31
Yes this is a duplicate of #1765

**Closed by easbar** 2020-05-11 17:31 UTC
